/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 static/wizards_room/house.glb -o /static/House.tsx -t -r public
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Mesh: THREE.Mesh;
    Mesh_1: THREE.Mesh;
    pPlane2: THREE.Mesh;
    pPlane6: THREE.Mesh;
    polySurface124: THREE.Mesh;
    Mesh005: THREE.Mesh;
    Mesh005_1: THREE.Mesh;
    Mesh016: THREE.Mesh;
    Mesh016_1: THREE.Mesh;
    polySurface369: THREE.Mesh;
    pCube150: THREE.Mesh;
    pCube210: THREE.Mesh;
    pCylinder70: THREE.Mesh;
    pCylinder71: THREE.Mesh;
    pCylinder72: THREE.Mesh;
    pCylinder73: THREE.Mesh;
    pCylinder74: THREE.Mesh;
    pCylinder75: THREE.Mesh;
    polySurface224: THREE.Mesh;
    Mesh023: THREE.Mesh;
    Mesh023_1: THREE.Mesh;
    Mesh037: THREE.Mesh;
    Mesh037_1: THREE.Mesh;
    Mesh037_2: THREE.Mesh;
    Mesh037_3: THREE.Mesh;
    pCube214: THREE.Mesh;
    pCube24: THREE.Mesh;
    Mesh035: THREE.Mesh;
    Mesh035_1: THREE.Mesh;
    Mesh036: THREE.Mesh;
    Mesh036_1: THREE.Mesh;
    Mesh038: THREE.Mesh;
    Mesh038_1: THREE.Mesh;
    polySurface251: THREE.Mesh;
    polySurface252: THREE.Mesh;
    polySurface253: THREE.Mesh;
    polySurface254: THREE.Mesh;
    polySurface255: THREE.Mesh;
    polySurface256: THREE.Mesh;
    pSphere31: THREE.Mesh;
    polySurface249: THREE.Mesh;
    polySurface263: THREE.Mesh;
    polySurface264: THREE.Mesh;
    polySurface265: THREE.Mesh;
    polySurface258: THREE.Mesh;
    polySurface378: THREE.Mesh;
    Mesh066: THREE.Mesh;
    Mesh066_1: THREE.Mesh;
    Mesh066_2: THREE.Mesh;
    polySurface480: THREE.Mesh;
    polySurface481: THREE.Mesh;
    polySurface385: THREE.Mesh;
    Mesh090: THREE.Mesh;
    Mesh090_1: THREE.Mesh;
    Mesh090_2: THREE.Mesh;
    Mesh090_3: THREE.Mesh;
    Mesh090_4: THREE.Mesh;
    Mesh085: THREE.Mesh;
    Mesh085_1: THREE.Mesh;
    Mesh085_2: THREE.Mesh;
    Mesh085_3: THREE.Mesh;
    Mesh085_4: THREE.Mesh;
    Mesh081: THREE.Mesh;
    Mesh081_1: THREE.Mesh;
    Mesh081_2: THREE.Mesh;
    Mesh081_3: THREE.Mesh;
    Mesh079: THREE.Mesh;
    Mesh079_1: THREE.Mesh;
    Mesh079_2: THREE.Mesh;
    Mesh084: THREE.Mesh;
    Mesh084_1: THREE.Mesh;
    Mesh084_2: THREE.Mesh;
    Mesh083: THREE.Mesh;
    Mesh083_1: THREE.Mesh;
    Mesh083_2: THREE.Mesh;
    Mesh086: THREE.Mesh;
    Mesh086_1: THREE.Mesh;
    Mesh086_2: THREE.Mesh;
    Mesh091: THREE.Mesh;
    Mesh091_1: THREE.Mesh;
    Mesh091_2: THREE.Mesh;
    Mesh092: THREE.Mesh;
    Mesh092_1: THREE.Mesh;
    Mesh093: THREE.Mesh;
    Mesh093_1: THREE.Mesh;
    Mesh094: THREE.Mesh;
    Mesh094_1: THREE.Mesh;
    Mesh094_2: THREE.Mesh;
    pPlane35: THREE.Mesh;
    pPlane50: THREE.Mesh;
    pPlane51: THREE.Mesh;
    pPlane52: THREE.Mesh;
    pPlane53: THREE.Mesh;
    pPlane54: THREE.Mesh;
    pPlane55: THREE.Mesh;
    pPlane56: THREE.Mesh;
    pPlane57: THREE.Mesh;
    Mesh082: THREE.Mesh;
    Mesh082_1: THREE.Mesh;
    Mesh082_2: THREE.Mesh;
    Mesh082_3: THREE.Mesh;
    Mesh080: THREE.Mesh;
    Mesh080_1: THREE.Mesh;
    Mesh080_2: THREE.Mesh;
    pCube50: THREE.Mesh;
    pCube126: THREE.Mesh;
    Mesh007: THREE.Mesh;
    Mesh007_1: THREE.Mesh;
    Mesh008: THREE.Mesh;
    Mesh008_1: THREE.Mesh;
    pCylinder32: THREE.Mesh;
    pPlane15: THREE.Mesh;
    Mesh011: THREE.Mesh;
    Mesh011_1: THREE.Mesh;
    Mesh012: THREE.Mesh;
    Mesh012_1: THREE.Mesh;
    Mesh012_2: THREE.Mesh;
    Mesh013: THREE.Mesh;
    Mesh013_1: THREE.Mesh;
    Mesh014: THREE.Mesh;
    Mesh014_1: THREE.Mesh;
    Mesh014_2: THREE.Mesh;
    Mesh015: THREE.Mesh;
    Mesh015_1: THREE.Mesh;
    Mesh017: THREE.Mesh;
    Mesh017_1: THREE.Mesh;
    polySurface284: THREE.Mesh;
    Mesh019: THREE.Mesh;
    Mesh019_1: THREE.Mesh;
    Mesh020: THREE.Mesh;
    Mesh020_1: THREE.Mesh;
    Mesh022: THREE.Mesh;
    Mesh022_1: THREE.Mesh;
    pCylinder82: THREE.Mesh;
    Mesh051: THREE.Mesh;
    Mesh051_1: THREE.Mesh;
    Mesh051_2: THREE.Mesh;
    Mesh052: THREE.Mesh;
    Mesh052_1: THREE.Mesh;
    Mesh052_2: THREE.Mesh;
    pPlane43: THREE.Mesh;
    polySurface345: THREE.Mesh;
    Mesh055: THREE.Mesh;
    Mesh055_1: THREE.Mesh;
    pCylinder83: THREE.Mesh;
    pCylinder84: THREE.Mesh;
    polySurface365: THREE.Mesh;
    polySurface366: THREE.Mesh;
    polySurface367: THREE.Mesh;
    polySurface368: THREE.Mesh;
    polySurface331: THREE.Mesh;
    Mesh064: THREE.Mesh;
    Mesh064_1: THREE.Mesh;
    Mesh064_2: THREE.Mesh;
    Mesh065: THREE.Mesh;
    Mesh065_1: THREE.Mesh;
    Mesh065_2: THREE.Mesh;
    Mesh065_3: THREE.Mesh;
    Mesh065_4: THREE.Mesh;
    Mesh065_5: THREE.Mesh;
    Mesh065_6: THREE.Mesh;
    Mesh069: THREE.Mesh;
    Mesh069_1: THREE.Mesh;
    Mesh069_2: THREE.Mesh;
    Mesh072: THREE.Mesh;
    Mesh072_1: THREE.Mesh;
    Mesh072_2: THREE.Mesh;
    Mesh074: THREE.Mesh;
    Mesh074_1: THREE.Mesh;
    polySurface395: THREE.Mesh;
    Mesh076: THREE.Mesh;
    Mesh076_1: THREE.Mesh;
    Mesh077: THREE.Mesh;
    Mesh077_1: THREE.Mesh;
    polySurface474: THREE.Mesh;
    polySurface478: THREE.Mesh;
    Mesh102: THREE.Mesh;
    Mesh102_1: THREE.Mesh;
    Mesh102_2: THREE.Mesh;
    pSphere33: THREE.Mesh;
    Mesh104: THREE.Mesh;
    Mesh104_1: THREE.Mesh;
    Mesh104_2: THREE.Mesh;
    Mesh105: THREE.Mesh;
    Mesh105_1: THREE.Mesh;
    Mesh105_2: THREE.Mesh;
  };
  materials: {
    Walls: THREE.MeshStandardMaterial;
    lambert11: THREE.MeshStandardMaterial;
    lambert12: THREE.MeshStandardMaterial;
    brown: THREE.MeshStandardMaterial;
    lambert21: THREE.MeshStandardMaterial;
    lambert7: THREE.MeshStandardMaterial;
    lambert19: THREE.MeshStandardMaterial;
    lambert29: THREE.MeshStandardMaterial;
    lambert28: THREE.MeshStandardMaterial;
    stown: THREE.MeshStandardMaterial;
    lambert4: THREE.MeshStandardMaterial;
    lambert14: THREE.MeshStandardMaterial;
    darkbrown: THREE.MeshStandardMaterial;
    ["lambert21.001"]: THREE.MeshStandardMaterial;
    lambert13: THREE.MeshStandardMaterial;
    lambert27: THREE.MeshStandardMaterial;
    lambert1: THREE.MeshStandardMaterial;
    lambert10: THREE.MeshStandardMaterial;
    lambert22: THREE.MeshStandardMaterial;
    lambert23: THREE.MeshStandardMaterial;
    lambert16: THREE.MeshStandardMaterial;
    CLASS: THREE.MeshStandardMaterial;
    ["CLASS.001"]: THREE.MeshStandardMaterial;
    lambert6: THREE.MeshStandardMaterial;
    lambert9: THREE.MeshStandardMaterial;
  };
};

const glassMat = new THREE.MeshPhysicalMaterial({
  color: 0xc7e3e1,
  roughness: 0,
  transmission: 0.95,
  reflectivity: 0,
  opacity: 0.6,
});

export function House(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/static/wizards_room/house.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group
        position={[-0.52, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.pPlane2.geometry}
          material={materials.lambert11}
        />
        <mesh
          geometry={nodes.pPlane6.geometry}
          material={materials.lambert12}
        />
        <mesh geometry={nodes.Mesh.geometry} material={materials.Walls} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials.lambert11} />
      </group>
      <group
        position={[-0.53, 0.18, 0]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.polySurface124.geometry}
          material={materials.brown}
          position={[-57.36, 38.72, -0.06]}
          scale={[1.31, 0.86, 1]}
        />
        <group position={[0, -2.25, 150.78]} scale={[1, 1, 2.22]}>
          <mesh geometry={nodes.Mesh005.geometry} material={materials.brown} />
          <mesh
            geometry={nodes.Mesh005_1.geometry}
            material={materials.lambert11}
          />
        </group>
      </group>
      <group
        position={[-1.79, -0.51, 0]}
        rotation={[-Math.PI / 2, 0.78, Math.PI]}
        scale={0.01}
      >
        <group
          position={[259.78, 132.07, 166.9]}
          rotation={[-0.08, 0, -0.08]}
          scale={[1.02, 1.16, 1.02]}
        >
          <mesh
            geometry={nodes.Mesh016.geometry}
            material={materials.lambert21}
          />
          <mesh
            geometry={nodes.Mesh016_1.geometry}
            material={materials.lambert7}
          />
        </group>
      </group>
      <group
        position={[-0.18, -0.44, 0.05]}
        rotation={[Math.PI / 2, 0.2, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.pCube150.geometry}
          material={materials.lambert19}
          position={[-95.5, 63.05, 61.93]}
          rotation={[-1.1, 0.25, 0.46]}
          scale={[0.59, 1, 1]}
        />
        <mesh
          geometry={nodes.pCube210.geometry}
          material={materials.lambert29}
          position={[-53.06, 0, -53.39]}
          rotation={[0, Math.PI / 6, 0]}
        />
        <mesh
          geometry={nodes.pCylinder70.geometry}
          material={materials.lambert28}
          position={[-119.6, 202.19, -4.32]}
          rotation={[0, 0, 1.44]}
          scale={1.11}
        />
        <mesh
          geometry={nodes.pCylinder71.geometry}
          material={materials.lambert28}
          position={[-71.05, 202.19, 8.44]}
          rotation={[0, -1.03, 1.44]}
          scale={1.11}
        />
        <mesh
          geometry={nodes.pCylinder72.geometry}
          material={materials.lambert28}
          position={[-57.51, 202.19, 58.24]}
          rotation={[-Math.PI, -1.04, -1.7]}
          scale={1.11}
        />
        <mesh
          geometry={nodes.pCylinder73.geometry}
          material={materials.lambert28}
          position={[-94.4, 202.19, 94.21]}
          rotation={[Math.PI, 0.02, -1.7]}
          scale={1.11}
        />
        <mesh
          geometry={nodes.pCylinder74.geometry}
          material={materials.lambert28}
          position={[-142.76, 202.19, 80.56]}
          rotation={[Math.PI, 1.05, -1.7]}
          scale={1.11}
        />
        <mesh
          geometry={nodes.pCylinder75.geometry}
          material={materials.lambert28}
          position={[-155.39, 202.19, 30.61]}
          rotation={[0, 1.03, 1.44]}
          scale={1.11}
        />
        <mesh
          geometry={nodes.polySurface224.geometry}
          material={materials.lambert28}
          position={[-53.06, 0, -53.39]}
          rotation={[0, Math.PI / 6, 0]}
        />
        <mesh geometry={nodes.Mesh023.geometry} material={materials.stown} />
        <mesh geometry={nodes.Mesh023_1.geometry} material={materials.brown} />
      </group>
      <group
        position={[-1.34, -0.12, 0.05]}
        rotation={[-Math.PI / 2, 1.32, Math.PI]}
        scale={0.01}
      >
        <group
          position={[7.76, 49.63, 84.45]}
          rotation={[0, 1.22, 0]}
          scale={0.84}
        >
          <mesh
            geometry={nodes.Mesh037.geometry}
            material={materials.lambert4}
          />
          <mesh
            geometry={nodes.Mesh037_1.geometry}
            material={materials.lambert7}
          />
          <mesh
            geometry={nodes.Mesh037_2.geometry}
            material={materials.lambert21}
          />
          <mesh
            geometry={nodes.Mesh037_3.geometry}
            material={materials.lambert14}
          />
        </group>
        <mesh
          geometry={nodes.pCube214.geometry}
          material={materials.darkbrown}
          position={[45.17, -4.72, 78.54]}
          rotation={[-Math.PI, 1.48, -Math.PI]}
          scale={1.11}
        />
        <mesh
          geometry={nodes.pCube24.geometry}
          material={materials.brown}
          position={[64.25, -11.2, -220.52]}
          rotation={[0, -0.22, 0]}
          scale={[0.95, 1.12, 0.87]}
        />
        <group position={[106.43, 48.84, -137.32]} scale={0.84}>
          <mesh
            geometry={nodes.Mesh035.geometry}
            material={materials["lambert21.001"]}
          />
          <mesh
            geometry={nodes.Mesh035_1.geometry}
            material={materials.lambert13}
          />
        </group>
        <group
          position={[59.94, 25.21, -136.98]}
          rotation={[0, 0.26, 1.07]}
          scale={[0.79, 0.61, 0.79]}
        >
          <mesh
            geometry={nodes.Mesh036.geometry}
            material={materials.lambert7}
          />
          <mesh
            geometry={nodes.Mesh036_1.geometry}
            material={materials.lambert27}
          />
        </group>
        <group
          position={[63.13, 1.25, 302.86]}
          rotation={[-Math.PI, 0.47, -Math.PI]}
          scale={[1.03, 1.34, 1.03]}
        >
          <mesh
            geometry={nodes.Mesh038.geometry}
            material={materials.lambert1}
          />
          {/* candle 2 to right */}
          <mesh
            geometry={nodes.Mesh038_1.geometry}
            material={materials.lambert7}
          />
        </group>
      </group>
      <group
        position={[-0.97, 0.17, 0.07]}
        rotation={[Math.PI / 2, 0.27, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.polySurface251.geometry}
          material={materials.lambert10}
          position={[1.1, -24.21, -74.59]}
        />
        <mesh
          geometry={nodes.polySurface252.geometry}
          material={materials.lambert10}
          position={[1.1, -24.21, -74.59]}
        />
        <mesh
          geometry={nodes.polySurface253.geometry}
          material={materials.lambert10}
          position={[1.1, -24.21, -74.59]}
        />
        <mesh
          geometry={nodes.polySurface254.geometry}
          material={materials.lambert21}
          position={[1.1, -24.21, -74.59]}
        />
        <mesh
          geometry={nodes.polySurface255.geometry}
          material={materials.lambert10}
          position={[1.1, -24.21, -74.59]}
        />
        <mesh
          geometry={nodes.polySurface256.geometry}
          material={materials.lambert10}
          position={[1.1, -24.21, -74.59]}
        />
        <mesh
          geometry={nodes.pSphere31.geometry}
          material={materials.lambert19}
          position={[34.92, 0, -54.54]}
        />
      </group>
      <group
        position={[-1.21, 0.63, 0.07]}
        rotation={[Math.PI / 2, 0.27, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.polySurface249.geometry}
          material={materials.lambert13}
          position={[111.59, 0, 41.34]}
        />
        <mesh
          geometry={nodes.polySurface263.geometry}
          material={materials.lambert12}
          position={[111.59, 0, 41.34]}
        />
        <mesh
          geometry={nodes.polySurface264.geometry}
          material={materials.lambert12}
          position={[90.32, 0, 51.16]}
          scale={[0.9, 1, 0.9]}
        />
        <mesh
          geometry={nodes.polySurface265.geometry}
          material={materials.lambert12}
          position={[100.42, -8.05, 46.5]}
          scale={[0.95, 1.05, 0.95]}
        />
      </group>
      <group
        position={[-0.54, 0.98, 0.13]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.polySurface258.geometry}
          material={materials.brown}
          position={[188.44, -11.19, 60.04]}
          scale={0.82}
        />
        <mesh
          geometry={nodes.polySurface378.geometry}
          material={materials.darkbrown}
          position={[43.98, 28.65, 63.46]}
          rotation={[0, -0.34, 0]}
        />
        <group position={[43.98, 33.76, 63.46]} rotation={[0, -0.34, 0]}>
          <mesh
            geometry={nodes.Mesh066.geometry}
            material={materials.darkbrown}
          />
          <mesh
            geometry={nodes.Mesh066_1.geometry}
            material={materials.lambert22}
          />
          <mesh
            geometry={nodes.Mesh066_2.geometry}
            material={materials.lambert11}
          />
        </group>
      </group>
      <group
        position={[-0.52, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.polySurface480.geometry}
          material={materials.lambert12}
          position={[0, 23.96, 0]}
        />
        <mesh
          geometry={nodes.polySurface481.geometry}
          material={materials.lambert12}
          position={[357.22, 604.88, -365.45]}
          rotation={[2.07, 0.59, 1.04]}
          scale={[2.24, 2.07, 2.31]}
        />
      </group>
      <group
        position={[-0.52, 0, 0.04]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <group
          position={[145.2, 115.83, -62.27]}
          rotation={[0, 0.57, 0]}
          scale={[0.72, 0.54, 0.72]}
        >
          <mesh
            geometry={nodes.Mesh090.geometry}
            material={materials.lambert14}
          />
          <mesh
            geometry={nodes.Mesh090_1.geometry}
            material={materials.lambert7}
          />
          <mesh
            geometry={nodes.Mesh090_2.geometry}
            material={materials.brown}
          />
          <mesh
            geometry={nodes.Mesh090_3.geometry}
            material={materials.lambert27}
          />
          <mesh
            geometry={nodes.Mesh090_4.geometry}
            material={materials.lambert22}
          />
        </group>
        <group
          position={[72.23, 49.15, -72.14]}
          rotation={[0, 0.5, 0]}
          scale={[0.84, 0.65, 0.84]}
        >
          <mesh
            geometry={nodes.Mesh085.geometry}
            material={materials.lambert16}
          />
          <mesh
            geometry={nodes.Mesh085_1.geometry}
            material={materials.lambert7}
          />
          <mesh
            geometry={nodes.Mesh085_2.geometry}
            material={materials.lambert21}
          />
          <mesh
            geometry={nodes.Mesh085_3.geometry}
            material={materials.lambert14}
          />
          <mesh
            geometry={nodes.Mesh085_4.geometry}
            material={materials.lambert27}
          />
        </group>
        <group
          position={[-24.54, 30.37, -37.34]}
          rotation={[2.73, 1.26, -2.71]}
          scale={0.81}
        >
          <mesh
            geometry={nodes.Mesh081.geometry}
            material={materials.lambert14}
          />
          <mesh
            geometry={nodes.Mesh081_1.geometry}
            material={materials.lambert7}
          />
          <mesh
            geometry={nodes.Mesh081_2.geometry}
            material={materials.lambert21}
          />
          <mesh
            geometry={nodes.Mesh081_3.geometry}
            material={materials.lambert23}
          />
        </group>
        <group
          position={[-217.7, -8, -126.79]}
          rotation={[0, 1.31, 0]}
          scale={[1, 0.98, 1]}
        >
          <mesh geometry={nodes.Mesh079.geometry} material={materials.brown} />
          <mesh
            geometry={nodes.Mesh079_1.geometry}
            material={materials.darkbrown}
          />
          <mesh
            geometry={nodes.Mesh079_2.geometry}
            material={materials.lambert21}
          />
        </group>
        <group
          position={[13.38, 64.26, -143.4]}
          rotation={[2.85, 0.74, -2.81]}
          scale={[0.43, 0.82, 0.43]}
        >
          <mesh
            geometry={nodes.Mesh084.geometry}
            material={materials.lambert12}
          />
          <mesh
            geometry={nodes.Mesh084_1.geometry}
            material={glassMat}
            // * inside the rag tube
          />
          <mesh
            geometry={nodes.Mesh084_2.geometry}
            material={materials.lambert13}
          />
        </group>
        <group
          position={[22.53, 51.88, -136.08]}
          rotation={[2.98, 0.75, -3.06]}
          scale={[0.43, 0.82, 0.43]}
        >
          <mesh
            geometry={nodes.Mesh083.geometry}
            material={materials.darkbrown}
          />
          <mesh
            geometry={nodes.Mesh083_1.geometry}
            material={glassMat}
            // * inside the rag tube2
          />
          <mesh
            geometry={nodes.Mesh083_2.geometry}
            material={materials.lambert13}
          />
        </group>
        <group
          position={[31.15, 51.88, -148.24]}
          rotation={[2.98, 0.75, -3.06]}
          scale={[0.43, 0.82, 0.43]}
        >
          <mesh
            geometry={nodes.Mesh086.geometry}
            material={materials.lambert12}
          />
          <mesh
            geometry={nodes.Mesh086_1.geometry}
            material={glassMat}
            // * inside the rag tube3
          />
          <mesh
            geometry={nodes.Mesh086_2.geometry}
            material={materials.lambert13}
          />
        </group>
        <group position={[3.65, 8.5, -0.46]} scale={[1, 0.93, 1]}>
          <mesh geometry={nodes.Mesh091.geometry} material={glassMat} />
          <mesh
            geometry={nodes.Mesh091_1.geometry}
            material={materials.darkbrown}
          />
          <mesh
            geometry={nodes.Mesh091_2.geometry}
            material={materials.lambert13}
          />
        </group>
        <group position={[34.25, 116.04, -52.34]} rotation={[0, 1.25, 0]}>
          <mesh
            geometry={nodes.Mesh092.geometry}
            material={materials.lambert7}
          />
          <mesh
            geometry={nodes.Mesh092_1.geometry}
            material={materials.lambert27}
          />
        </group>
        <group position={[115.79, 116.04, -178.44]} rotation={[0, -1.05, 0]}>
          <mesh
            geometry={nodes.Mesh093.geometry}
            material={materials.lambert7}
          />
          <mesh
            geometry={nodes.Mesh093_1.geometry}
            material={materials.lambert27}
          />
        </group>
        <group
          position={[94.78, 25.1, 118.24]}
          rotation={[1.71, -0.05, 1.75]}
          scale={[1, 1, 0.92]}
        >
          <mesh
            geometry={nodes.Mesh094.geometry}
            material={materials.lambert7}
          />
          <mesh
            geometry={nodes.Mesh094_1.geometry}
            material={materials.lambert21}
          />
          <mesh
            geometry={nodes.Mesh094_2.geometry}
            material={materials.lambert14}
          />
        </group>
        <mesh
          geometry={nodes.pPlane35.geometry}
          material={materials.lambert7}
          position={[323.64, 387.03, -59.11]}
          rotation={[2.08, -1.04, 0.52]}
          scale={[1.16, 0.84, 1.16]}
        />
        <mesh
          geometry={nodes.pPlane50.geometry}
          material={materials.lambert7}
          position={[262.27, -70.19, -102.75]}
          rotation={[-1.61, -0.34, 2.88]}
          scale={[1, 0.73, 1]}
        />
        <mesh
          geometry={nodes.pPlane51.geometry}
          material={materials.lambert7}
          position={[222.85, -85.97, -52.54]}
          rotation={[-1.72, -0.28, 2.66]}
          scale={[1, 0.83, 1]}
        />
        <mesh
          geometry={nodes.pPlane52.geometry}
          material={materials.lambert7}
          position={[226.36, -25.82, -103.86]}
          rotation={[-1.61, -0.34, 2.88]}
          scale={[0.77, 0.73, 0.77]}
        />
        <mesh
          geometry={nodes.pPlane53.geometry}
          material={materials.lambert7}
          position={[-107, 184.99, -172.36]}
          rotation={[1.1, 1.1, 0.58]}
          scale={[0.77, 0.73, 0.77]}
        />
        <mesh
          geometry={nodes.pPlane54.geometry}
          material={materials.lambert7}
          position={[-179.06, 199.86, -191.39]}
          rotation={[1.1, 1.1, 0.58]}
          scale={[1, 0.73, 1]}
        />
        <mesh
          geometry={nodes.pPlane55.geometry}
          material={materials.lambert7}
          position={[286.01, 115.1, -152.98]}
          rotation={[-0.29, -1.45, -0.87]}
          scale={[0.68, 0.44, 0.68]}
        />
        <mesh
          geometry={nodes.pPlane56.geometry}
          material={materials.lambert7}
          position={[258.82, 195.55, -146.82]}
          rotation={[1.5, -1.11, 1.07]}
          scale={[0.68, 0.44, 0.68]}
        />
        <mesh
          geometry={nodes.pPlane57.geometry}
          material={materials.lambert7}
          position={[223.45, 142.04, -150.09]}
          rotation={[0.86, -1.28, 0.26]}
          scale={[0.52, 0.44, 0.52]}
        />
        <group position={[64.58, 15.96, 42.94]} rotation={[0, -1.26, 0]}>
          <mesh geometry={nodes.Mesh082.geometry} material={materials.Walls} />
          <mesh
            geometry={nodes.Mesh082_1.geometry}
            material={materials.lambert7}
          />
          <mesh
            geometry={nodes.Mesh082_2.geometry}
            material={materials.lambert11}
          />
          <mesh
            geometry={nodes.Mesh082_3.geometry}
            material={materials.lambert22}
          />
        </group>
        <group position={[64.58, 29.29, 42.94]} rotation={[0, -1.26, 0]}>
          <mesh geometry={nodes.Mesh080.geometry} material={materials.Walls} />
          <mesh
            geometry={nodes.Mesh080_1.geometry}
            material={materials.lambert7}
          />
          <mesh
            geometry={nodes.Mesh080_2.geometry}
            material={materials.lambert11}
          />
        </group>
      </group>
      <mesh
        geometry={nodes.pCube50.geometry}
        material={materials.brown}
        position={[-1.14, 1.41, 1.03]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.004, 0.01, 0.01]}
      />
      <mesh
        geometry={nodes.pCube126.geometry}
        material={materials.brown}
        position={[-1.14, 1.39, 1.42]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.004, 0.01, 0.01]}
      />
      <group
        position={[-0.62, 1.58, 1.51]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[0, 0.01, 0.01]}
      >
        <mesh geometry={nodes.Mesh007.geometry} material={materials.Walls} />
        <mesh
          geometry={nodes.Mesh007_1.geometry}
          material={materials.lambert11}
        />
      </group>
      <group
        position={[1.28, -3.27, 0.1]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={0.01}
      >
        <mesh geometry={nodes.Mesh008.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.Mesh008_1.geometry} material={materials.brown} />
      </group>
      <mesh
        geometry={nodes.pCylinder32.geometry}
        material={materials.brown}
        position={[-1.96, 3.74, 3.24]}
        rotation={[1.77, 0.08, -1.59]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.pPlane15.geometry}
        material={materials.lambert7}
        position={[-0.21, -0.46, 0.04]}
        rotation={[-Math.PI / 2, 0.48, Math.PI]}
        scale={0.01}
      />
      <group
        position={[-0.52, 4.11, 1.04]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.Mesh011.geometry}
          material={materials.lambert22}
        />
        <mesh geometry={nodes.Mesh011_1.geometry} material={materials.stown} />
      </group>
      <group
        position={[0.52, 0.8, 0.7]}
        rotation={[-Math.PI / 2, 0.12, Math.PI]}
        scale={[0.009, 0.007, 0.009]}
      >
        <mesh
          geometry={nodes.Mesh012.geometry}
          material={materials.lambert27}
        />
        <mesh
          geometry={nodes.Mesh012_1.geometry}
          material={materials.lambert7}
        />
        <mesh
          geometry={nodes.Mesh012_2.geometry}
          material={materials.lambert21}
        />
      </group>
      <group
        position={[-0.47, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh geometry={nodes.Mesh013.geometry} material={materials.Walls} />
        <mesh
          geometry={nodes.Mesh013_1.geometry}
          material={materials.lambert11}
        />
      </group>
      <group
        position={[0.07, 1.61, 0.21]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.008}
      >
        <mesh geometry={nodes.Mesh014.geometry} material={glassMat} />
        <mesh
          geometry={nodes.Mesh014_1.geometry}
          material={materials.lambert12}
        />
        <mesh
          geometry={nodes.Mesh014_2.geometry}
          material={materials.lambert29}
        />
      </group>
      <group
        position={[0.12, 1.52, 0.22]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.008}
      >
        <mesh geometry={nodes.Mesh015.geometry} material={glassMat} />
        <mesh
          geometry={nodes.Mesh015_1.geometry}
          material={materials.darkbrown}
        />
      </group>
      <group
        position={[-0.55, -1.02, 0.05]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={0.01}
      >
        <mesh geometry={nodes.Mesh017.geometry} material={materials.stown} />
        <mesh geometry={nodes.Mesh017_1.geometry} material={materials.brown} />
      </group>
      <mesh
        geometry={nodes.polySurface284.geometry}
        material={materials.lambert12}
        position={[-1.5, 2.47, 0.06]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <group
        position={[-0.52, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.Mesh019.geometry}
          material={materials.darkbrown}
        />
        <mesh
          geometry={nodes.Mesh019_1.geometry}
          material={materials.lambert11}
        />
      </group>
      <group
        position={[-0.47, -0.03, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.Mesh020.geometry}
          material={materials.darkbrown}
        />
        <mesh
          geometry={nodes.Mesh020_1.geometry}
          material={materials.lambert11}
        />
      </group>
      <group
        position={[-0.85, 0.04, -0.33]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={0.01}
      >
        <mesh geometry={nodes.Mesh022.geometry} material={materials.stown} />
        <mesh
          geometry={nodes.Mesh022_1.geometry}
          material={materials.lambert21}
        />
      </group>
      <mesh
        geometry={nodes.pCylinder82.geometry}
        material={materials.lambert19}
        position={[1.82, 1.98, 0.04]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      />
      <group
        position={[-0.521792, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh geometry={nodes.Mesh051.geometry} material={glassMat} />
        <mesh
          geometry={nodes.Mesh051_1.geometry}
          material={materials.lambert13}
        />
        <mesh
          geometry={nodes.Mesh051_2.geometry}
          material={materials.lambert12}
        />
      </group>
      <group
        position={[-0.52, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.001}
      >
        <mesh geometry={nodes.Mesh052.geometry} material={glassMat} />
        <mesh
          geometry={nodes.Mesh052_1.geometry}
          material={materials.lambert12}
        />
        <mesh
          geometry={nodes.Mesh052_2.geometry}
          material={materials.lambert4}
        />
      </group>
      <mesh
        geometry={nodes.pPlane43.geometry}
        material={materials.lambert7}
        position={[0.18, 2.3, 2.13]}
        rotation={[2.21, -0.96, -1.02]}
        scale={0.0062}
      />
      <group
        position={[0.22, -1.1, -0.75]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.017}
      >
        <mesh geometry={nodes.polySurface345.geometry} material={glassMat} />
        {/* <mesh geometry={nodes.polySurface345.geometry} material={glassMat} /> */}
      </group>
      <group
        position={[-0.52, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
        //* candle 1 from left
      >
        <mesh geometry={nodes.Mesh055.geometry} material={materials.lambert7} />
        <mesh
          geometry={nodes.Mesh055_1.geometry}
          material={materials.lambert1}
        />
      </group>
      <mesh
        geometry={nodes.pCylinder83.geometry}
        material={materials.lambert19}
        position={[2.24, 2.36, 1.03]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.015}
      />
      <mesh
        geometry={nodes.pCylinder84.geometry}
        material={materials.lambert19}
        position={[2.65, 2.36, 1]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.0145}
      />
      <mesh
        geometry={nodes.polySurface365.geometry}
        material={materials.lambert1}
        position={[-0.41, 2.05, 1.68]}
        rotation={[1.55, 0.51, 1.29]}
        scale={0.01}
        //* 1st butterfly
      />
      <mesh
        geometry={nodes.polySurface366.geometry}
        material={materials.lambert1}
        position={[1.8, 1.13, 2.08]}
        rotation={[1.55, -0.84, 1.27]}
        scale={0.007}
      />
      <mesh
        geometry={nodes.polySurface367.geometry}
        material={materials.lambert1}
        position={[0.02, 1.15, 1.46]}
        rotation={[1.2, 0.49, 1.95]}
        scale={0.0067}
      />
      <mesh
        geometry={nodes.polySurface368.geometry}
        material={materials.lambert1}
        position={[-0.32, 1.32, 1.55]}
        rotation={[1.27, 0.74, 2.01]}
        scale={0.007}
      />
      <mesh
        geometry={nodes.polySurface331.geometry}
        material={materials.darkbrown}
        position={[-0.52, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <group
        position={[-0.52, 0.74, -0.01]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.Mesh064.geometry}
          material={materials.darkbrown}
        />
        <mesh
          geometry={nodes.Mesh064_1.geometry}
          material={materials.lambert21}
        />
        <mesh geometry={nodes.Mesh064_2.geometry} material={glassMat} />
      </group>
      <group
        position={[-0.52, 0, -0.01]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.Mesh065.geometry}
          material={materials.lambert21}
        />
        <mesh geometry={nodes.Mesh065_1.geometry} material={materials.Walls} />
        <mesh
          geometry={nodes.Mesh065_2.geometry}
          material={materials.lambert7}
        />
        <mesh
          geometry={nodes.Mesh065_3.geometry}
          material={materials.lambert11}
        />
        <mesh
          geometry={nodes.Mesh065_4.geometry}
          material={materials.lambert14}
        />
        <mesh
          geometry={nodes.Mesh065_5.geometry}
          material={materials.lambert9}
        />
        <mesh
          geometry={nodes.Mesh065_6.geometry}
          material={materials.lambert22}
        />
      </group>
      <group
        position={[-1.47, -0.58, 0.05]}
        rotation={[Math.PI / 2, -0.63, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.Mesh069.geometry}
          material={materials.lambert27}
        />
        <mesh
          geometry={nodes.Mesh069_1.geometry}
          material={materials.lambert7}
        />
        <mesh
          geometry={nodes.Mesh069_2.geometry}
          material={materials.lambert21}
        />
      </group>
      <group
        position={[-0.52, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.Mesh072.geometry}
          material={materials.lambert23}
        />
        <mesh
          geometry={nodes.Mesh072_1.geometry}
          material={materials.lambert1}
        />
        <mesh
          geometry={nodes.Mesh072_2.geometry}
          material={materials.lambert7}
        />
      </group>
      <group
        position={[-0.41, -0.22, 0.16]}
        rotation={[1.45, 0.01, -0.05]}
        scale={[0.009, 0.01, 0.009]}
      >
        <mesh geometry={nodes.Mesh074.geometry} material={materials.lambert1} />
        <mesh
          geometry={nodes.Mesh074_1.geometry}
          material={materials.lambert7}
        />
      </group>
      <mesh
        geometry={nodes.polySurface395.geometry}
        material={materials.lambert23}
        position={[-0.55, -0.85, 0.05]}
        rotation={[-Math.PI / 2, -1.46, -3.05]}
        scale={0.01}
      />
      <group
        position={[-0.52, 0, 0.04]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.Mesh076.geometry}
          material={materials.lambert21}
        />
        <mesh
          geometry={nodes.Mesh076_1.geometry}
          material={materials.lambert7}
        />
      </group>
      <group
        position={[-0.52, 0, 0.04]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.Mesh077.geometry}
          material={materials.lambert21}
        />
        <mesh
          geometry={nodes.Mesh077_1.geometry}
          material={materials.lambert7}
        />
      </group>
      <mesh
        geometry={nodes.polySurface474.geometry}
        material={materials.stown}
        position={[-0.52, 0, 0.05]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.polySurface478.geometry}
        material={materials.lambert23}
        position={[-0.52, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <group
        position={[-1.64, -1.23, -0.18]}
        rotation={[Math.PI / 2, 1.46, 0]}
        scale={0.0083}
      >
        <mesh geometry={nodes.Mesh102.geometry} material={glassMat} />
        <mesh
          geometry={nodes.Mesh102_1.geometry}
          material={materials.lambert12}
        />
        {/* <mesh
          geometry={nodes.Mesh102_2.geometry}
          material={materials.lambert29}
        /> */}
      </group>
      <mesh
        geometry={nodes.pSphere33.geometry}
        material={materials.Walls}
        position={[1.56, 0.73, 1.01]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.008}
      />
      <group
        position={[1.4, -2.68, -0.47]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh geometry={nodes.Mesh104.geometry} material={glassMat} />
        <mesh
          geometry={nodes.Mesh104_1.geometry}
          material={materials.lambert13}
        />
        <mesh
          geometry={nodes.Mesh104_2.geometry}
          material={materials.lambert12}
        />
      </group>
      <group
        position={[-0.52, 0, 0]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      >
        <mesh geometry={nodes.Mesh105.geometry} material={glassMat} />
        <mesh
          geometry={nodes.Mesh105_1.geometry}
          material={materials.lambert12}
        />
        <mesh
          geometry={nodes.Mesh105_2.geometry}
          material={materials.lambert10}
        />
      </group>
      <mesh
        geometry={nodes.polySurface369.geometry}
        material={materials.lambert12}
        position={[-0.58, -0.01, 0.08]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.polySurface385.geometry}
        material={materials.lambert23}
        position={[2.63, 0.12, 0.12]}
        rotation={[1.37, 1.2, 0.39]}
        scale={0.01}
      />
    </group>
  );
}

useGLTF.preload("/static/wizards_room/house.glb");
