/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 static/Animations/Nitin.glb -o Character.tsx -T -t -r public
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_10001: THREE.SkinnedMesh;
    Object_10002: THREE.SkinnedMesh;
    Object_11001: THREE.SkinnedMesh;
    Object_12001: THREE.SkinnedMesh;
    Object_13001: THREE.SkinnedMesh;
    Object_13002: THREE.SkinnedMesh;
    Object_14001: THREE.SkinnedMesh;
    Object_14002: THREE.SkinnedMesh;
    Object_15001: THREE.SkinnedMesh;
    Object_16001: THREE.SkinnedMesh;
    Object_16002: THREE.SkinnedMesh;
    Object_17001: THREE.SkinnedMesh;
    Object_17002: THREE.SkinnedMesh;
    Object_18001: THREE.SkinnedMesh;
    Object_18002: THREE.SkinnedMesh;
    Object_19001: THREE.SkinnedMesh;
    Object_2001: THREE.SkinnedMesh;
    Object_2002: THREE.SkinnedMesh;
    Object_20001: THREE.SkinnedMesh;
    Object_20002: THREE.SkinnedMesh;
    Object_21001: THREE.SkinnedMesh;
    Object_21002: THREE.SkinnedMesh;
    Object_21003: THREE.SkinnedMesh;
    Object_22001: THREE.SkinnedMesh;
    Object_22002: THREE.SkinnedMesh;
    Object_23001: THREE.SkinnedMesh;
    Object_23002: THREE.SkinnedMesh;
    Object_24001: THREE.SkinnedMesh;
    Object_24002: THREE.SkinnedMesh;
    Object_24003: THREE.SkinnedMesh;
    Object_25001: THREE.SkinnedMesh;
    Object_25002: THREE.SkinnedMesh;
    Object_26001: THREE.SkinnedMesh;
    Object_26003: THREE.SkinnedMesh;
    Object_27001: THREE.SkinnedMesh;
    Object_27002: THREE.SkinnedMesh;
    Object_27003: THREE.SkinnedMesh;
    Object_28001: THREE.SkinnedMesh;
    Object_28002: THREE.SkinnedMesh;
    Object_28003: THREE.SkinnedMesh;
    Object_29001: THREE.SkinnedMesh;
    Object_29002: THREE.SkinnedMesh;
    Object_29003: THREE.SkinnedMesh;
    Object_3001: THREE.SkinnedMesh;
    Object_30001: THREE.SkinnedMesh;
    Object_30002: THREE.SkinnedMesh;
    Object_30003: THREE.SkinnedMesh;
    Object_30004: THREE.SkinnedMesh;
    Object_31001: THREE.SkinnedMesh;
    Object_31002: THREE.SkinnedMesh;
    Object_31004: THREE.SkinnedMesh;
    Object_31005: THREE.SkinnedMesh;
    Object_32001: THREE.SkinnedMesh;
    Object_32002: THREE.SkinnedMesh;
    Object_32003: THREE.SkinnedMesh;
    Object_33001: THREE.SkinnedMesh;
    Object_34001: THREE.SkinnedMesh;
    Object_34002: THREE.SkinnedMesh;
    Object_35001: THREE.SkinnedMesh;
    Object_36001: THREE.SkinnedMesh;
    Object_36002: THREE.SkinnedMesh;
    Object_37001: THREE.SkinnedMesh;
    Object_38001: THREE.SkinnedMesh;
    Object_39001: THREE.SkinnedMesh;
    Object_4001: THREE.SkinnedMesh;
    Object_4002: THREE.SkinnedMesh;
    Object_40001: THREE.SkinnedMesh;
    Object_41001: THREE.SkinnedMesh;
    Object_42001: THREE.SkinnedMesh;
    Object_43001: THREE.SkinnedMesh;
    Object_44001: THREE.SkinnedMesh;
    Object_45001: THREE.SkinnedMesh;
    Object_46001: THREE.SkinnedMesh;
    Object_47001: THREE.SkinnedMesh;
    Object_48001: THREE.SkinnedMesh;
    Object_49001: THREE.SkinnedMesh;
    Object_5001: THREE.SkinnedMesh;
    Object_50001: THREE.SkinnedMesh;
    Object_51001: THREE.SkinnedMesh;
    Object_52001: THREE.SkinnedMesh;
    Object_53001: THREE.SkinnedMesh;
    Object_54001: THREE.SkinnedMesh;
    Object_55001: THREE.SkinnedMesh;
    Object_56001: THREE.SkinnedMesh;
    Object_57001: THREE.SkinnedMesh;
    Object_58001: THREE.SkinnedMesh;
    Object_59001: THREE.SkinnedMesh;
    Object_6001: THREE.SkinnedMesh;
    Object_60001: THREE.SkinnedMesh;
    Object_61001: THREE.SkinnedMesh;
    Object_62001: THREE.SkinnedMesh;
    Object_63001: THREE.SkinnedMesh;
    Object_64001: THREE.SkinnedMesh;
    Object_65001: THREE.SkinnedMesh;
    Object_66001: THREE.SkinnedMesh;
    Object_67001: THREE.SkinnedMesh;
    Object_68001: THREE.SkinnedMesh;
    Object_68002: THREE.SkinnedMesh;
    Object_69001: THREE.SkinnedMesh;
    Object_69002: THREE.SkinnedMesh;
    Object_7001: THREE.SkinnedMesh;
    Object_70001: THREE.SkinnedMesh;
    Object_71001: THREE.SkinnedMesh;
    Object_72001: THREE.SkinnedMesh;
    Object_73001: THREE.SkinnedMesh;
    Object_74001: THREE.SkinnedMesh;
    Object_75001: THREE.SkinnedMesh;
    Object_76001: THREE.SkinnedMesh;
    Object_77001: THREE.SkinnedMesh;
    Object_78001: THREE.SkinnedMesh;
    Object_79001: THREE.SkinnedMesh;
    Object_8001: THREE.SkinnedMesh;
    Object_80001: THREE.SkinnedMesh;
    Object_81001: THREE.SkinnedMesh;
    Object_81002: THREE.SkinnedMesh;
    Object_81003: THREE.SkinnedMesh;
    Object_81004: THREE.SkinnedMesh;
    Object_81005: THREE.SkinnedMesh;
    Object_82001: THREE.SkinnedMesh;
    Object_82002: THREE.SkinnedMesh;
    Object_82003: THREE.SkinnedMesh;
    Object_82004: THREE.SkinnedMesh;
    Object_9001: THREE.SkinnedMesh;
    mixamorigHips: THREE.Bone;
  };
  materials: {
    metals: THREE.MeshStandardMaterial;
    GOLDEN: THREE.MeshStandardMaterial;
    BLACK: THREE.MeshStandardMaterial;
    WORDS: THREE.MeshStandardMaterial;
    darkbrown: THREE.MeshStandardMaterial;
    PINK: THREE.MeshStandardMaterial;
    PAPER: THREE.MeshStandardMaterial;
    GRAY: THREE.MeshStandardMaterial;
    EYES: THREE.MeshStandardMaterial;
    Cloth: THREE.MeshStandardMaterial;
    GLOVES: THREE.MeshStandardMaterial;
    SKIN: THREE.MeshStandardMaterial;
  };
};

type ActionName =
  | "Armature.008|Armature|mixamo.com|Layer0_Armature.001"
  | "Armature|mixamo.com|Layer0"
  | "Armature|mixamo.com|Layer0_Armature_Armature.001"
  | "BALANCE"
  | "BALL_2"
  | "BALL_3"
  | "BALL"
  | "CONTACT"
  | "FLYING"
  | "IDLE"
  | "JUMP"
  | "LOOKBACK"
  | "SITTING_IDLE"
  | "SKILL"
  | "STARTER"
  | "WORK";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

const eyesMat = <meshStandardMaterial color="#E7B192"></meshStandardMaterial>;
console.log(eyesMat);
export default function Nitin(props: JSX.IntrinsicElements["group"]) {
  const group = useRef<THREE.Group>(null);
  const { nodes, materials, animations } = useGLTF(
    "/../Nitin-transformed.glb"
  ) as GLTFResult;
  const { actions } = useAnimations<THREE.AnimationClip>(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature001">
          <primitive object={nodes.mixamorigHips} />
          <group name="Object_31003" />
          <skinnedMesh
            name="Object_10001"
            geometry={nodes.Object_10001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_10001.skeleton}
          />
          <skinnedMesh
            name="Object_10002"
            geometry={nodes.Object_10002.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_10002.skeleton}
          />
          <skinnedMesh
            name="Object_11001"
            geometry={nodes.Object_11001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_11001.skeleton}
          />
          <skinnedMesh
            name="Object_12001"
            geometry={nodes.Object_12001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_12001.skeleton}
          />
          <skinnedMesh
            name="Object_13001"
            geometry={nodes.Object_13001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_13001.skeleton}
          />
          <skinnedMesh
            name="Object_13002"
            geometry={nodes.Object_13002.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_13002.skeleton}
          />
          <skinnedMesh
            name="Object_14001"
            geometry={nodes.Object_14001.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_14001.skeleton}
          />
          <skinnedMesh
            name="Object_14002"
            geometry={nodes.Object_14002.geometry}
            material={materials.metals}
            skeleton={nodes.Object_14002.skeleton}
          />
          <skinnedMesh
            name="Object_15001"
            geometry={nodes.Object_15001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_15001.skeleton}
          />
          <skinnedMesh
            name="Object_16001"
            geometry={nodes.Object_16001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_16001.skeleton}
          />
          <skinnedMesh
            name="Object_16002"
            geometry={nodes.Object_16002.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_16002.skeleton}
          />
          <skinnedMesh
            name="Object_17001"
            geometry={nodes.Object_17001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_17001.skeleton}
          />
          <skinnedMesh
            name="Object_17002"
            geometry={nodes.Object_17002.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_17002.skeleton}
          />
          <skinnedMesh
            name="Object_18001"
            geometry={nodes.Object_18001.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_18001.skeleton}
          />
          <skinnedMesh
            name="Object_18002"
            geometry={nodes.Object_18002.geometry}
            material={materials.metals}
            skeleton={nodes.Object_18002.skeleton}
          />
          <skinnedMesh
            name="Object_19001"
            geometry={nodes.Object_19001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_19001.skeleton}
          />
          <skinnedMesh
            name="Object_2001"
            geometry={nodes.Object_2001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_2001.skeleton}
          />
          <skinnedMesh
            name="Object_2002"
            geometry={nodes.Object_2002.geometry}
            material={materials.BLACK}
            skeleton={nodes.Object_2002.skeleton}
          />
          <skinnedMesh
            name="Object_20001"
            geometry={nodes.Object_20001.geometry}
            material={materials.WORDS}
            skeleton={nodes.Object_20001.skeleton}
          />
          <skinnedMesh
            name="Object_20002"
            geometry={nodes.Object_20002.geometry}
            material={materials.metals}
            skeleton={nodes.Object_20002.skeleton}
          />
          <skinnedMesh
            name="Object_21001"
            geometry={nodes.Object_21001.geometry}
            material={materials.WORDS}
            skeleton={nodes.Object_21001.skeleton}
          />
          <skinnedMesh
            name="Object_21002"
            geometry={nodes.Object_21002.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_21002.skeleton}
          />
          <skinnedMesh
            name="Object_21003"
            geometry={nodes.Object_21003.geometry}
            material={materials.metals}
            skeleton={nodes.Object_21003.skeleton}
          />
          <skinnedMesh
            name="Object_22001"
            geometry={nodes.Object_22001.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_22001.skeleton}
          />
          <skinnedMesh
            name="Object_22002"
            geometry={nodes.Object_22002.geometry}
            material={materials.metals}
            skeleton={nodes.Object_22002.skeleton}
          />
          <skinnedMesh
            name="Object_23001"
            geometry={nodes.Object_23001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_23001.skeleton}
          />
          <skinnedMesh
            name="Object_23002"
            geometry={nodes.Object_23002.geometry}
            material={materials.WORDS}
            skeleton={nodes.Object_23002.skeleton}
          />
          <skinnedMesh
            name="Object_24001"
            geometry={nodes.Object_24001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_24001.skeleton}
          />
          <skinnedMesh
            name="Object_24002"
            geometry={nodes.Object_24002.geometry}
            material={materials.WORDS}
            skeleton={nodes.Object_24002.skeleton}
          />
          <skinnedMesh
            name="Object_24003"
            geometry={nodes.Object_24003.geometry}
            material={materials.darkbrown}
            skeleton={nodes.Object_24003.skeleton}
          />
          <skinnedMesh
            name="Object_25001"
            geometry={nodes.Object_25001.geometry}
            material={materials.BLACK}
            skeleton={nodes.Object_25001.skeleton}
          />
          <skinnedMesh
            name="Object_25002"
            geometry={nodes.Object_25002.geometry}
            material={materials.WORDS}
            skeleton={nodes.Object_25002.skeleton}
          />
          <skinnedMesh
            name="Object_26001"
            geometry={nodes.Object_26001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_26001.skeleton}
          />
          <skinnedMesh
            name="Object_26003"
            geometry={nodes.Object_26003.geometry}
            material={materials.metals}
            skeleton={nodes.Object_26003.skeleton}
          />
          <skinnedMesh
            name="Object_27001"
            geometry={nodes.Object_27001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_27001.skeleton}
          />
          <skinnedMesh
            name="Object_27002"
            geometry={nodes.Object_27002.geometry}
            material={materials.metals}
            skeleton={nodes.Object_27002.skeleton}
          />
          <skinnedMesh
            name="Object_27003"
            geometry={nodes.Object_27003.geometry}
            material={materials.WORDS}
            skeleton={nodes.Object_27003.skeleton}
          />
          <skinnedMesh
            name="Object_28001"
            geometry={nodes.Object_28001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_28001.skeleton}
          />
          <skinnedMesh
            name="Object_28002"
            geometry={nodes.Object_28002.geometry}
            material={materials.WORDS}
            skeleton={nodes.Object_28002.skeleton}
          />
          <skinnedMesh
            name="Object_28003"
            geometry={nodes.Object_28003.geometry}
            material={materials.WORDS}
            skeleton={nodes.Object_28003.skeleton}
          />
          <skinnedMesh
            name="Object_29001"
            geometry={nodes.Object_29001.geometry}
            material={materials.PAPER}
            skeleton={nodes.Object_29001.skeleton}
          />
          <skinnedMesh
            name="Object_29002"
            geometry={nodes.Object_29002.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_29002.skeleton}
          />
          <skinnedMesh
            name="Object_29003"
            geometry={nodes.Object_29003.geometry}
            material={materials.WORDS}
            skeleton={nodes.Object_29003.skeleton}
          />
          <skinnedMesh
            name="Object_3001"
            geometry={nodes.Object_3001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_3001.skeleton}
          />
          <skinnedMesh
            name="Object_30001"
            geometry={nodes.Object_30001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_30001.skeleton}
          />
          <skinnedMesh
            name="Object_30002"
            geometry={nodes.Object_30002.geometry}
            material={materials.metals}
            skeleton={nodes.Object_30002.skeleton}
          />
          <skinnedMesh
            name="Object_30003"
            geometry={nodes.Object_30003.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_30003.skeleton}
          />
          <skinnedMesh
            name="Object_30004"
            geometry={nodes.Object_30004.geometry}
            material={materials.WORDS}
            skeleton={nodes.Object_30004.skeleton}
          />
          <skinnedMesh
            name="Object_31001"
            geometry={nodes.Object_31001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_31001.skeleton}
          />
          <skinnedMesh
            name="Object_31002"
            geometry={nodes.Object_31002.geometry}
            material={materials.metals}
            skeleton={nodes.Object_31002.skeleton}
          />
          <skinnedMesh
            name="Object_31004"
            geometry={nodes.Object_31004.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_31004.skeleton}
          />
          <skinnedMesh
            name="Object_31005"
            geometry={nodes.Object_31005.geometry}
            material={materials.WORDS}
            skeleton={nodes.Object_31005.skeleton}
          />
          <skinnedMesh
            name="Object_32001"
            geometry={nodes.Object_32001.geometry}
            material={materials.PAPER}
            skeleton={nodes.Object_32001.skeleton}
          />
          <skinnedMesh
            name="Object_32002"
            geometry={nodes.Object_32002.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_32002.skeleton}
          />
          <skinnedMesh
            name="Object_32003"
            geometry={nodes.Object_32003.geometry}
            material={materials.WORDS}
            skeleton={nodes.Object_32003.skeleton}
          />
          <skinnedMesh
            name="Object_33001"
            geometry={nodes.Object_33001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_33001.skeleton}
          />
          <skinnedMesh
            name="Object_34001"
            geometry={nodes.Object_34001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_34001.skeleton}
          />
          <skinnedMesh
            name="Object_34002"
            geometry={nodes.Object_34002.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_34002.skeleton}
          />
          <skinnedMesh
            name="Object_35001"
            geometry={nodes.Object_35001.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_35001.skeleton}
          />
          <skinnedMesh
            name="Object_36001"
            geometry={nodes.Object_36001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_36001.skeleton}
          />
          <skinnedMesh
            name="Object_36002"
            geometry={nodes.Object_36002.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_36002.skeleton}
          />
          <skinnedMesh
            name="Object_37001"
            geometry={nodes.Object_37001.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_37001.skeleton}
          />
          <skinnedMesh
            name="Object_38001"
            geometry={nodes.Object_38001.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_38001.skeleton}
          />
          <skinnedMesh
            name="Object_39001"
            geometry={nodes.Object_39001.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_39001.skeleton}
          />
          <skinnedMesh
            name="Object_4001"
            geometry={nodes.Object_4001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_4001.skeleton}
          />
          <skinnedMesh
            name="Object_4002"
            geometry={nodes.Object_4002.geometry}
            material={materials.metals}
            skeleton={nodes.Object_4002.skeleton}
          />
          <skinnedMesh
            name="Object_40001"
            geometry={nodes.Object_40001.geometry}
            material={materials.WORDS}
            skeleton={nodes.Object_40001.skeleton}
          />
          <skinnedMesh
            name="Object_41001"
            geometry={nodes.Object_41001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_41001.skeleton}
          />
          <skinnedMesh
            name="Object_42001"
            geometry={nodes.Object_42001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_42001.skeleton}
          />
          <skinnedMesh
            name="Object_43001"
            geometry={nodes.Object_43001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_43001.skeleton}
          />
          <skinnedMesh
            name="Object_44001"
            geometry={nodes.Object_44001.geometry}
            material={materials.GRAY}
            skeleton={nodes.Object_44001.skeleton}
          />
          <skinnedMesh
            name="Object_45001"
            geometry={nodes.Object_45001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_45001.skeleton}
          />
          <skinnedMesh
            name="Object_46001"
            geometry={nodes.Object_46001.geometry}
            material={materials.GRAY}
            skeleton={nodes.Object_46001.skeleton}
          />
          <skinnedMesh
            name="Object_47001"
            geometry={nodes.Object_47001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_47001.skeleton}
          />
          <skinnedMesh
            name="Object_48001"
            geometry={nodes.Object_48001.geometry}
            material={materials.GRAY}
            skeleton={nodes.Object_48001.skeleton}
          />
          <skinnedMesh
            name="Object_49001"
            geometry={nodes.Object_49001.geometry}
            material={eyesMat.props.material}
            skeleton={nodes.Object_49001.skeleton}
          />
          <skinnedMesh
            name="Object_5001"
            geometry={nodes.Object_5001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_5001.skeleton}
          />
          <skinnedMesh
            name="Object_50001"
            geometry={nodes.Object_50001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_50001.skeleton}
          />
          <skinnedMesh
            name="Object_51001"
            geometry={nodes.Object_51001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_51001.skeleton}
          />
          <skinnedMesh
            name="Object_52001"
            geometry={nodes.Object_52001.geometry}
            material={materials.BLACK}
            skeleton={nodes.Object_52001.skeleton}
          />
          <skinnedMesh
            name="Object_53001"
            geometry={nodes.Object_53001.geometry}
            material={materials.Cloth}
            skeleton={nodes.Object_53001.skeleton}
          />
          <skinnedMesh
            name="Object_54001"
            geometry={nodes.Object_54001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_54001.skeleton}
          />
          <skinnedMesh
            name="Object_55001"
            geometry={nodes.Object_55001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_55001.skeleton}
          />
          <skinnedMesh
            name="Object_56001"
            geometry={nodes.Object_56001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_56001.skeleton}
          />
          <skinnedMesh
            name="Object_57001"
            geometry={nodes.Object_57001.geometry}
            material={materials.GLOVES}
            skeleton={nodes.Object_57001.skeleton}
          />
          <skinnedMesh
            name="Object_58001"
            geometry={nodes.Object_58001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_58001.skeleton}
          />
          <skinnedMesh
            name="Object_59001"
            geometry={nodes.Object_59001.geometry}
            material={materials.BLACK}
            skeleton={nodes.Object_59001.skeleton}
          />
          <skinnedMesh
            name="Object_6001"
            geometry={nodes.Object_6001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_6001.skeleton}
          />
          <skinnedMesh
            name="Object_60001"
            geometry={nodes.Object_60001.geometry}
            material={materials.BLACK}
            skeleton={nodes.Object_60001.skeleton}
          />
          <skinnedMesh
            name="Object_61001"
            geometry={nodes.Object_61001.geometry}
            material={materials.Cloth}
            skeleton={nodes.Object_61001.skeleton}
          />
          <skinnedMesh
            name="Object_62001"
            geometry={nodes.Object_62001.geometry}
            material={materials.BLACK}
            skeleton={nodes.Object_62001.skeleton}
          />
          <skinnedMesh
            name="Object_63001"
            geometry={nodes.Object_63001.geometry}
            material={materials.BLACK}
            skeleton={nodes.Object_63001.skeleton}
          />
          <skinnedMesh
            name="Object_64001"
            geometry={nodes.Object_64001.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_64001.skeleton}
          />
          <skinnedMesh
            name="Object_65001"
            geometry={nodes.Object_65001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_65001.skeleton}
          />
          <skinnedMesh
            name="Object_66001"
            geometry={nodes.Object_66001.geometry}
            material={materials.BLACK}
            skeleton={nodes.Object_66001.skeleton}
          />
          <skinnedMesh
            name="Object_67001"
            geometry={nodes.Object_67001.geometry}
            material={materials.GLOVES}
            skeleton={nodes.Object_67001.skeleton}
          />
          <skinnedMesh
            name="Object_68001"
            geometry={nodes.Object_68001.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_68001.skeleton}
          />
          <skinnedMesh
            name="Object_68002"
            geometry={nodes.Object_68002.geometry}
            material={materials.darkbrown}
            skeleton={nodes.Object_68002.skeleton}
          />
          <skinnedMesh
            name="Object_69001"
            geometry={nodes.Object_69001.geometry}
            material={materials.darkbrown}
            skeleton={nodes.Object_69001.skeleton}
          />
          <skinnedMesh
            name="Object_69002"
            geometry={nodes.Object_69002.geometry}
            material={materials.Cloth}
            skeleton={nodes.Object_69002.skeleton}
          />
          <skinnedMesh
            name="Object_7001"
            geometry={nodes.Object_7001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_7001.skeleton}
          />
          <skinnedMesh
            name="Object_70001"
            geometry={nodes.Object_70001.geometry}
            material={materials.GLOVES}
            skeleton={nodes.Object_70001.skeleton}
          />
          <skinnedMesh
            name="Object_71001"
            geometry={nodes.Object_71001.geometry}
            material={materials.BLACK}
            skeleton={nodes.Object_71001.skeleton}
          />
          <skinnedMesh
            name="Object_72001"
            geometry={nodes.Object_72001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_72001.skeleton}
          />
          <skinnedMesh
            name="Object_73001"
            geometry={nodes.Object_73001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_73001.skeleton}
          />
          <skinnedMesh
            name="Object_74001"
            geometry={nodes.Object_74001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_74001.skeleton}
          />
          <skinnedMesh
            name="Object_75001"
            geometry={nodes.Object_75001.geometry}
            material={materials.darkbrown}
            skeleton={nodes.Object_75001.skeleton}
          />
          <skinnedMesh
            name="Object_76001"
            geometry={nodes.Object_76001.geometry}
            material={materials.SKIN}
            skeleton={nodes.Object_76001.skeleton}
          />
          <skinnedMesh
            name="Object_77001"
            geometry={nodes.Object_77001.geometry}
            material={materials.Cloth}
            skeleton={nodes.Object_77001.skeleton}
          />
          <skinnedMesh
            name="Object_78001"
            geometry={nodes.Object_78001.geometry}
            material={materials.Cloth}
            skeleton={nodes.Object_78001.skeleton}
          />
          <skinnedMesh
            name="Object_79001"
            geometry={nodes.Object_79001.geometry}
            material={materials.PINK}
            skeleton={nodes.Object_79001.skeleton}
          />
          <skinnedMesh
            name="Object_8001"
            geometry={nodes.Object_8001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_8001.skeleton}
          />
          <skinnedMesh
            name="Object_80001"
            geometry={nodes.Object_80001.geometry}
            material={materials.darkbrown}
            skeleton={nodes.Object_80001.skeleton}
          />
          <skinnedMesh
            name="Object_81001"
            geometry={nodes.Object_81001.geometry}
            material={materials.darkbrown}
            skeleton={nodes.Object_81001.skeleton}
          />
          <skinnedMesh
            name="Object_81002"
            geometry={nodes.Object_81002.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_81002.skeleton}
          />
          <skinnedMesh
            name="Object_81003"
            geometry={nodes.Object_81003.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_81003.skeleton}
          />
          <skinnedMesh
            name="Object_81004"
            geometry={nodes.Object_81004.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_81004.skeleton}
          />
          <skinnedMesh
            name="Object_81005"
            geometry={nodes.Object_81005.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_81005.skeleton}
          />
          <skinnedMesh
            name="Object_82001"
            geometry={nodes.Object_82001.geometry}
            material={materials.darkbrown}
            skeleton={nodes.Object_82001.skeleton}
          />
          <skinnedMesh
            name="Object_82002"
            geometry={nodes.Object_82002.geometry}
            material={materials.darkbrown}
            skeleton={nodes.Object_82002.skeleton}
          />
          <skinnedMesh
            name="Object_82003"
            geometry={nodes.Object_82003.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_82003.skeleton}
          />
          <skinnedMesh
            name="Object_82004"
            geometry={nodes.Object_82004.geometry}
            material={materials.GOLDEN}
            skeleton={nodes.Object_82004.skeleton}
          />
          <skinnedMesh
            name="Object_9001"
            geometry={nodes.Object_9001.geometry}
            material={materials.metals}
            skeleton={nodes.Object_9001.skeleton}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/../Nitin-transformed.glb");
