/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 static/wizards_room/final_room.glb -o House.tsx -t -r public
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import {
  useGLTF,
  useAnimations,
  Sparkles,
  Float,
  useScroll,
} from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";
import { useGSAP } from "@gsap/react";
import { useControls } from "leva";

type GLTFResult = GLTF & {
  nodes: {
    Mesh: THREE.Mesh;
    Mesh_1: THREE.Mesh;
    pPlane2: THREE.Mesh;
    pPlane6: THREE.Mesh;
    polySurface124: THREE.Mesh;
    Mesh005: THREE.Mesh;
    Mesh005_1: THREE.Mesh;
    Mesh016: THREE.Mesh;
    Mesh016_1: THREE.Mesh;
    polySurface369: THREE.Mesh;
    pCube150: THREE.Mesh;
    pCube210: THREE.Mesh;
    pCube210001: THREE.Mesh;
    pCube210002: THREE.Mesh;
    pCube210003: THREE.Mesh;
    pCube210004: THREE.Mesh;
    pCube210005: THREE.Mesh;
    pCube210006: THREE.Mesh;
    pCylinder70: THREE.Mesh;
    pCylinder71: THREE.Mesh;
    pCylinder72: THREE.Mesh;
    pCylinder73: THREE.Mesh;
    pCylinder74: THREE.Mesh;
    pCylinder75: THREE.Mesh;
    polySurface224: THREE.Mesh;
    Mesh023: THREE.Mesh;
    Mesh023_1: THREE.Mesh;
    pCube214: THREE.Mesh;
    Mesh037: THREE.Mesh;
    Mesh037_1: THREE.Mesh;
    Mesh037_2: THREE.Mesh;
    Mesh037_3: THREE.Mesh;
    pCube24: THREE.Mesh;
    pCylinder79: THREE.Mesh;
    pCylinder79001: THREE.Mesh;
    Mesh036: THREE.Mesh;
    Mesh036_1: THREE.Mesh;
    Mesh038: THREE.Mesh;
    Mesh038_1: THREE.Mesh;
    polySurface251: THREE.Mesh;
    polySurface252: THREE.Mesh;
    polySurface253: THREE.Mesh;
    polySurface254: THREE.Mesh;
    polySurface255: THREE.Mesh;
    polySurface256: THREE.Mesh;
    pSphere31: THREE.Mesh;
    polySurface249: THREE.Mesh;
    polySurface263: THREE.Mesh;
    polySurface264: THREE.Mesh;
    polySurface265: THREE.Mesh;
    polySurface258: THREE.Mesh;
    polySurface378: THREE.Mesh;
    Mesh066: THREE.Mesh;
    Mesh066_1: THREE.Mesh;
    Mesh066_2: THREE.Mesh;
    polySurface480: THREE.Mesh;
    polySurface481: THREE.Mesh;
    polySurface385: THREE.Mesh;
    Mesh090: THREE.Mesh;
    Mesh090_1: THREE.Mesh;
    Mesh090_2: THREE.Mesh;
    Mesh090_3: THREE.Mesh;
    Mesh090_4: THREE.Mesh;
    Mesh085: THREE.Mesh;
    Mesh085_1: THREE.Mesh;
    Mesh085_2: THREE.Mesh;
    Mesh085_3: THREE.Mesh;
    Mesh085_4: THREE.Mesh;
    Mesh081: THREE.Mesh;
    Mesh081_1: THREE.Mesh;
    Mesh081_2: THREE.Mesh;
    Mesh081_3: THREE.Mesh;
    Mesh079: THREE.Mesh;
    Mesh079_1: THREE.Mesh;
    Mesh079_2: THREE.Mesh;
    Mesh084: THREE.Mesh;
    Mesh084_1: THREE.Mesh;
    Mesh084_2: THREE.Mesh;
    polySurface376: THREE.Mesh;
    polySurface376001: THREE.Mesh;
    Mesh086: THREE.Mesh;
    Mesh086_1: THREE.Mesh;
    Mesh086_2: THREE.Mesh;
    Mesh091: THREE.Mesh;
    Mesh091_1: THREE.Mesh;
    Mesh091_2: THREE.Mesh;
    Mesh092: THREE.Mesh;
    Mesh092_1: THREE.Mesh;
    Mesh093: THREE.Mesh;
    Mesh093_1: THREE.Mesh;
    Mesh094: THREE.Mesh;
    Mesh094_1: THREE.Mesh;
    Mesh094_2: THREE.Mesh;
    pPlane35: THREE.Mesh;
    pPlane50: THREE.Mesh;
    pPlane51: THREE.Mesh;
    pPlane52: THREE.Mesh;
    pPlane53: THREE.Mesh;
    pPlane54: THREE.Mesh;
    pPlane55: THREE.Mesh;
    pPlane56: THREE.Mesh;
    pPlane57: THREE.Mesh;
    Mesh082: THREE.Mesh;
    Mesh082_1: THREE.Mesh;
    Mesh082_2: THREE.Mesh;
    Mesh082_3: THREE.Mesh;
    Mesh080: THREE.Mesh;
    Mesh080_1: THREE.Mesh;
    Mesh080_2: THREE.Mesh;
    pCube50: THREE.Mesh;
    pCube126: THREE.Mesh;
    Mesh007: THREE.Mesh;
    Mesh007_1: THREE.Mesh;
    Mesh008: THREE.Mesh;
    Mesh008_1: THREE.Mesh;
    pCylinder32: THREE.Mesh;
    pPlane15: THREE.Mesh;
    Mesh011: THREE.Mesh;
    Mesh011_1: THREE.Mesh;
    Mesh012: THREE.Mesh;
    Mesh012_1: THREE.Mesh;
    Mesh012_2: THREE.Mesh;
    Mesh013: THREE.Mesh;
    Mesh013_1: THREE.Mesh;
    Mesh014: THREE.Mesh;
    Mesh014_1: THREE.Mesh;
    Mesh014_2: THREE.Mesh;
    Mesh015: THREE.Mesh;
    Mesh015_1: THREE.Mesh;
    Mesh017: THREE.Mesh;
    Mesh017_1: THREE.Mesh;
    polySurface284: THREE.Mesh;
    Mesh019: THREE.Mesh;
    Mesh019_1: THREE.Mesh;
    Mesh020: THREE.Mesh;
    Mesh020_1: THREE.Mesh;
    Mesh022: THREE.Mesh;
    Mesh022_1: THREE.Mesh;
    pCylinder82: THREE.Mesh;
    Mesh051: THREE.Mesh;
    Mesh051_1: THREE.Mesh;
    Mesh051_2: THREE.Mesh;
    Mesh052: THREE.Mesh;
    Mesh052_1: THREE.Mesh;
    Mesh052_2: THREE.Mesh;
    pPlane43: THREE.Mesh;
    polySurface345: THREE.Mesh;
    Mesh055: THREE.Mesh;
    Mesh055_1: THREE.Mesh;
    pCylinder83: THREE.Mesh;
    pCylinder84: THREE.Mesh;
    polySurface365: THREE.Mesh;
    polySurface366: THREE.Mesh;
    polySurface367: THREE.Mesh;
    polySurface368: THREE.Mesh;
    polySurface331: THREE.Mesh;
    Mesh064: THREE.Mesh;
    Mesh064_1: THREE.Mesh;
    Mesh064_2: THREE.Mesh;
    Mesh065: THREE.Mesh;
    Mesh065_1: THREE.Mesh;
    Mesh065_2: THREE.Mesh;
    Mesh065_3: THREE.Mesh;
    Mesh065_4: THREE.Mesh;
    Mesh065_5: THREE.Mesh;
    Mesh065_6: THREE.Mesh;
    Mesh069: THREE.Mesh;
    Mesh069_1: THREE.Mesh;
    Mesh069_2: THREE.Mesh;
    Mesh072: THREE.Mesh;
    Mesh072_1: THREE.Mesh;
    Mesh072_2: THREE.Mesh;
    Mesh074: THREE.Mesh;
    Mesh074_1: THREE.Mesh;
    polySurface395: THREE.Mesh;
    Mesh076: THREE.Mesh;
    Mesh076_1: THREE.Mesh;
    Mesh077: THREE.Mesh;
    Mesh077_1: THREE.Mesh;
    polySurface474: THREE.Mesh;
    polySurface478: THREE.Mesh;
    Mesh102: THREE.Mesh;
    Mesh102_1: THREE.Mesh;
    Mesh102_2: THREE.Mesh;
    pSphere33: THREE.Mesh;
    Mesh104: THREE.Mesh;
    Mesh104_1: THREE.Mesh;
    Mesh104_2: THREE.Mesh;
    Mesh105: THREE.Mesh;
    Mesh105_1: THREE.Mesh;
    Mesh105_2: THREE.Mesh;
    polySurface345001: THREE.Mesh;
    polySurface482001: THREE.Mesh;
    polySurface345002: THREE.Mesh;
  };
  materials: {
    Walls: THREE.MeshStandardMaterial;
    lambert11: THREE.MeshStandardMaterial;
    lambert12: THREE.MeshStandardMaterial;
    brown: THREE.MeshStandardMaterial;
    lambert21: THREE.MeshStandardMaterial;
    lambert7: THREE.MeshStandardMaterial;
    lambert19: THREE.MeshStandardMaterial;
    lambert29: THREE.MeshStandardMaterial;
    lambert28: THREE.MeshStandardMaterial;
    stown: THREE.MeshStandardMaterial;
    darkbrown: THREE.MeshStandardMaterial;
    lambert4: THREE.MeshStandardMaterial;
    lambert14: THREE.MeshStandardMaterial;
    lambert13: THREE.MeshStandardMaterial;
    lambert27: THREE.MeshStandardMaterial;
    lambert1: THREE.MeshStandardMaterial;
    lambert10: THREE.MeshStandardMaterial;
    lambert22: THREE.MeshStandardMaterial;
    lambert23: THREE.MeshStandardMaterial;
    lambert16: THREE.MeshStandardMaterial;
    CLASS: THREE.MeshStandardMaterial;
    lambert6: THREE.MeshStandardMaterial;
    lambert9: THREE.MeshStandardMaterial;
  };
};

type ActionName =
  | "tube_1"
  | "jar_3"
  | "pot_spoon"
  | "pot_water"
  | "drop_1"
  | "drop_2"
  | "drop_3"
  | "drop_4"
  | "big_cube_2"
  | "big_cube_1"
  | "chair"
  | "jar_2"
  | "jar_1"
  | "butterfly_1"
  | "butterfly_4"
  | "butterfly_2"
  | "butterfly_3"
  | "tube_3"
  | "tube_2"
  | "jar_4"
  | "jar_5"
  | "tube_2.001";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

const glassMat = new THREE.MeshPhysicalMaterial({
  color: 0xc7e3e1,
  roughness: 0,
  transmission: 0.95,
  reflectivity: 0,
  opacity: 0.6,
});

const names = [
  "tube_1",
  "jar_3",
  "pot_spoon",
  "pot_water",
  "drop_1",
  "drop_2",
  "drop_3",
  "drop_4",
  "big_cube_2",
  "big_cube_1",
  "chair",
  "jar_2",
  "jar_1",
  "butterfly_1",
  "butterfly_4",
  "butterfly_2",
  "butterfly_3",
  "tube_3",
  "tube_2",
  "jar_4",
  "jar_5",
  "tube_2.001",
];

type roomType = JSX.IntrinsicElements["group"] & {
  roomRef: React.MutableRefObject<THREE.Group | null>;
};

const roomHeight = 15;
const no_pages = 3;

function Room({ roomRef, ...props }: roomType) {
  const { nodes, materials, animations } = useGLTF(
    "/static/wizards_room/final_room.glb"
  ) as GLTFResult;
  const { actions } = useAnimations<THREE.AnimationClip>(animations, roomRef);
  const broomRef = useRef<THREE.Mesh | null>(null!);
  const tl = useRef<GSAPTimeline | null>(null);
  const scroll = useScroll();

  const { min, max, speed, intensity } = useControls({
    min: { value: 1, min: 0, max: 10 },
    max: { value: 3, min: 0, max: 10 },
    speed: { value: 1, min: 0, max: 10 },
    intensity: {
      value: 0.000001,
      min: 0.0000000000000001,
      max: 10,
      step: 0.000001,
    },
  });

  useGSAP(
    () => {
      tl.current = gsap.timeline();
      if (tl.current && roomRef.current) {
        tl.current
          .to(
            roomRef.current.rotation,
            {
              duration: 2,
              x: -Math.PI / 2,
              z: 0,
              ease: "sine.in",
            },
            0
          )
          .to(
            roomRef.current.position,
            {
              duration: 2,
              x: -10,
              z: -5,
              overwrite: "auto",
              ease: "sine.in",
            },
            0
          );
        tl.current
          .to(roomRef.current.scale, {
            duration: 2,
            x: 11,
            y: 11,
            z: 11,
            ease: "sine.in",
          })
          .to(
            roomRef.current.position,
            {
              duration: 2,
              x: -10,
              z: -10,
              overwrite: "auto",
              ease: "sine.in",
            },
            "<"
          );

        tl.current.to(
          roomRef.current.position,
          {
            duration: 5,
            y: -40,
          },
          0
        );
        tl.current.to(
          roomRef.current.position,
          {
            duration: 10,
            x: 20,
            overwrite: "auto",
          },
          "-=3"
        );
      }
      if (tl.current && broomRef.current) {
        tl.current.to(
          broomRef.current.position,
          {
            duration: 3,
            x: -2.5,
            y: 0.708041,
            z: -0.2,
          },
          "-=8.5"
        );
        tl.current.to(
          broomRef.current.position,
          {
            duration: 8,
            x: -3.2,
            y: 0.5,
            z: -2.4,
            overwrite: "auto",
          },
          "<"
        );
      }
    },
    { scope: roomRef }
  );

  useEffect(() => {
    names.forEach((name) => {
      if (
        name !== "drop_1" &&
        name !== "drop_2" &&
        name !== "drop_3" &&
        name !== "drop_4" &&
        name !== "big_cube_2" &&
        name !== "big_cube_1" &&
        name !== "butterfly_1" &&
        name !== "butterfly_4" &&
        name !== "butterfly_2" &&
        name !== "butterfly_3" &&
        name !== "pot_water" &&
        name !== "pot_spoon"
      ) {
        if (actions[name]) {
          actions[name]!.repetitions = 1;

          actions[name]?.setDuration(10).fadeIn(0.5).play();

          return () => {
            actions[name]?.fadeOut(0.5).stop();
          };
        }
      } else {
        actions[name]?.setDuration(5).reset().fadeIn(5).play();

        return () => {
          actions[name]?.fadeOut(5);
        };
      }
    });
  }, [actions, names]);

  useFrame((state, delta) => {
    // console.log(scroll.offset, broomRef.current?.position);

    if (scroll.offset > 0.72 && broomRef.current) {
      // console.log(Math.sin((scroll.offset * -delta * 100) / 10));
      if (broomRef.current.rotation.y <= scroll.offset) {
        broomRef.current.rotation.y = scroll.offset * -30;
      } else {
        broomRef.current.rotation.y += -delta;
      }
    } else if (scroll.offset <= 0.78 && broomRef.current) {
      if (broomRef.current.rotation.y < 0) {
        broomRef.current.rotation.y = scroll.offset * 30;
      } else {
        broomRef.current.rotation.y = 0;
      }
    }
    if (tl.current) tl.current.seek(scroll.offset * tl.current.duration());
  });
  return (
    <group ref={roomRef} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="mage_room"
          position={[4.48, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group name="pPlane1">
            <group name="polySurface126">
              <mesh
                name="Mesh"
                geometry={nodes.Mesh.geometry}
                material={materials.Walls}
              />
              <mesh
                name="Mesh_1"
                geometry={nodes.Mesh_1.geometry}
                material={materials.lambert11}
              />
            </group>
          </group>
          <mesh
            name="pPlane2"
            geometry={nodes.pPlane2.geometry}
            material={materials.lambert11}
          />
          <mesh
            name="pPlane6"
            geometry={nodes.pPlane6.geometry}
            material={materials.lambert12}
          >
            <group name="transform2" />
          </mesh>
        </group>
        <group
          name="pCube63"
          position={[4.47, 0.18, 0]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={0.01}
        >
          <mesh
            name="polySurface124"
            geometry={nodes.polySurface124.geometry}
            material={materials.brown}
            position={[-57.36, 38.72, -0.06]}
            scale={[1.31, 0.86, 1]}
          />
          <group
            name="polySurface177"
            position={[0, -2.25, 150.78]}
            scale={[1, 1, 2.22]}
          >
            <mesh
              name="Mesh005"
              geometry={nodes.Mesh005.geometry}
              material={materials.brown}
            />
            <mesh
              name="Mesh005_1"
              geometry={nodes.Mesh005_1.geometry}
              material={materials.lambert11}
            />
          </group>
        </group>
        <group
          name="stairss"
          position={[3.21, -0.51, 0]}
          rotation={[-Math.PI / 2, 0.78, Math.PI]}
          scale={0.01}
        >
          <group
            name="pSphere17"
            position={[259.78, 132.07, 166.9]}
            rotation={[-0.08, 0, -0.08]}
            scale={[1.02, 1.16, 1.02]}
          >
            <mesh
              name="Mesh016"
              geometry={nodes.Mesh016.geometry}
              material={materials.lambert21}
            />
            <mesh
              name="Mesh016_1"
              geometry={nodes.Mesh016_1.geometry}
              material={materials.lambert7}
            />
          </group>
        </group>
        <group
          name="pTorus13"
          position={[4.42, -0.01, 0.08]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="polySurface369"
            geometry={nodes.polySurface369.geometry}
            material={materials.lambert12}
          />
        </group>
        <group
          name="Pot"
          position={[4.82, -0.44, 0.05]}
          rotation={[Math.PI / 2, 0.2, 0]}
          scale={0.01}
        >
          <mesh
            name="pCube150"
            geometry={nodes.pCube150.geometry}
            material={materials.lambert19}
            position={[-95.5, 63.05, 61.93]}
            rotation={[-1.1, 0.25, 0.46]}
            scale={[0.59, 1, 1]}
          />
          <mesh
            name="pCube210"
            geometry={nodes.pCube210.geometry}
            material={materials.lambert29}
            position={[-53.06, 0, -53.39]}
            rotation={[0, Math.PI / 6, 0]}
          />
          <mesh
            name="pCube210001"
            geometry={nodes.pCube210001.geometry}
            material={materials.lambert29}
            position={[-53.06, 0, -53.39]}
            rotation={[0, Math.PI / 6, 0]}
          />
          <mesh
            name="pCube210002"
            geometry={nodes.pCube210002.geometry}
            material={materials.lambert29}
            position={[-53.06, 0, -53.39]}
            rotation={[0, Math.PI / 6, 0]}
          />
          <mesh
            name="pCube210003"
            geometry={nodes.pCube210003.geometry}
            material={materials.lambert29}
            position={[-53.06, -5.68, -53.39]}
            rotation={[0, Math.PI / 6, 0]}
          />
          <mesh
            name="pCube210004"
            geometry={nodes.pCube210004.geometry}
            material={materials.lambert29}
            position={[-53.06, 0, -53.39]}
            rotation={[0, Math.PI / 6, 0]}
          />
          <mesh
            name="pCube210005"
            geometry={nodes.pCube210005.geometry}
            material={materials.lambert29}
            position={[-53.06, -8.08, -53.39]}
            rotation={[0, Math.PI / 6, 0]}
          />
          <mesh
            name="pCube210006"
            geometry={nodes.pCube210006.geometry}
            material={materials.lambert29}
            position={[-53.06, -8.18, -53.39]}
            rotation={[0, Math.PI / 6, 0]}
          />
          <mesh
            name="pCylinder70"
            geometry={nodes.pCylinder70.geometry}
            material={materials.lambert28}
            position={[-119.6, 202.19, -4.32]}
            rotation={[0, 0, 1.44]}
            scale={1.11}
          />
          <mesh
            name="pCylinder71"
            geometry={nodes.pCylinder71.geometry}
            material={materials.lambert28}
            position={[-71.05, 202.19, 8.44]}
            rotation={[0, -1.03, 1.44]}
            scale={1.11}
          />
          <mesh
            name="pCylinder72"
            geometry={nodes.pCylinder72.geometry}
            material={materials.lambert28}
            position={[-57.51, 202.19, 58.24]}
            rotation={[-Math.PI, -1.04, -1.7]}
            scale={1.11}
          />
          <mesh
            name="pCylinder73"
            geometry={nodes.pCylinder73.geometry}
            material={materials.lambert28}
            position={[-94.4, 202.19, 94.21]}
            rotation={[Math.PI, 0.02, -1.7]}
            scale={1.11}
          />
          <mesh
            name="pCylinder74"
            geometry={nodes.pCylinder74.geometry}
            material={materials.lambert28}
            position={[-142.76, 202.19, 80.56]}
            rotation={[Math.PI, 1.05, -1.7]}
            scale={1.11}
          />
          <mesh
            name="pCylinder75"
            geometry={nodes.pCylinder75.geometry}
            material={materials.lambert28}
            position={[-155.39, 202.19, 30.61]}
            rotation={[0, 1.03, 1.44]}
            scale={1.11}
          />
          <mesh
            name="polySurface224"
            geometry={nodes.polySurface224.geometry}
            material={materials.lambert28}
            position={[-53.06, 0, -53.39]}
            rotation={[0, Math.PI / 6, 0]}
          />
          <group name="polySurface268">
            <mesh
              name="Mesh023"
              geometry={nodes.Mesh023.geometry}
              material={materials.stown}
            />
            <mesh
              name="Mesh023_1"
              geometry={nodes.Mesh023_1.geometry}
              material={materials.brown}
            />
          </group>
        </group>
        <group
          name="Tablegroup"
          position={[3.66, -0.12, 0.05]}
          rotation={[-Math.PI / 2, 1.32, Math.PI]}
          scale={0.01}
        >
          <mesh
            name="pCube214"
            geometry={nodes.pCube214.geometry}
            material={materials.darkbrown}
            position={[45.17, -4.72, 78.54]}
            rotation={[-Math.PI, 1.48, -Math.PI]}
            scale={1.11}
          />
          <group
            name="books2_polySurface199"
            position={[7.76, 49.63, 84.45]}
            rotation={[0, 1.22, 0]}
            scale={0.84}
          >
            <mesh
              name="Mesh037"
              geometry={nodes.Mesh037.geometry}
              material={materials.lambert4}
            />
            <mesh
              name="Mesh037_1"
              geometry={nodes.Mesh037_1.geometry}
              material={materials.lambert7}
            />
            <mesh
              name="Mesh037_2"
              geometry={nodes.Mesh037_2.geometry}
              material={materials.lambert21}
            />
            <mesh
              name="Mesh037_3"
              geometry={nodes.Mesh037_3.geometry}
              material={materials.lambert14}
            />
          </group>
          <mesh
            name="pCube24"
            geometry={nodes.pCube24.geometry}
            material={materials.brown}
            position={[64.25, -11.2, -220.52]}
            rotation={[0, -0.22, 0]}
            scale={[0.95, 1.12, 0.87]}
          />
          <mesh
            name="pCylinder79"
            geometry={nodes.pCylinder79.geometry}
            material={materials.lambert13}
            position={[106.43, 48.84, -137.32]}
            scale={0.84}
          />
          <mesh
            name="pCylinder79001"
            geometry={nodes.pCylinder79001.geometry}
            material={materials.lambert21}
            position={[106.43, 48.84, -137.32]}
            scale={0.84}
          />
          <group
            name="polySurface222"
            position={[59.94, 25.21, -136.98]}
            rotation={[0, 0.26, 1.07]}
            scale={[0.79, 0.61, 0.79]}
          >
            <mesh
              name="Mesh036"
              geometry={nodes.Mesh036.geometry}
              material={materials.lambert7}
            />
            <mesh
              name="Mesh036_1"
              geometry={nodes.Mesh036_1.geometry}
              material={materials.lambert27}
            />
          </group>
          <group
            name="pPlane42"
            position={[63.13, 1.25, 302.86]}
            rotation={[-Math.PI, 0.47, -Math.PI]}
            scale={[1.031, 1.338, 1.031]}
          >
            <mesh
              name="Mesh038"
              geometry={nodes.Mesh038.geometry}
              material={materials.lambert1}
            />
            <mesh
              name="Mesh038_1"
              geometry={nodes.Mesh038_1.geometry}
              material={materials.lambert7}
            />
          </group>
        </group>
        <group
          name="pot11"
          position={[4.03, 0.17, 0.07]}
          rotation={[Math.PI / 2, 0.27, 0]}
          scale={0.01}
        >
          <mesh
            name="polySurface251"
            geometry={nodes.polySurface251.geometry}
            material={materials.lambert10}
            position={[1.1, -24.21, -74.59]}
          />
          <mesh
            name="polySurface252"
            geometry={nodes.polySurface252.geometry}
            material={materials.lambert10}
            position={[1.1, -24.21, -74.59]}
          />
          <mesh
            name="polySurface253"
            geometry={nodes.polySurface253.geometry}
            material={materials.lambert10}
            position={[1.1, -24.21, -74.59]}
          />
          <mesh
            name="polySurface254"
            geometry={nodes.polySurface254.geometry}
            material={materials.lambert21}
            position={[1.1, -24.21, -74.59]}
          />
          <mesh
            name="polySurface255"
            geometry={nodes.polySurface255.geometry}
            material={materials.lambert10}
            position={[1.1, -24.21, -74.59]}
          />
          <mesh
            name="polySurface256"
            geometry={nodes.polySurface256.geometry}
            material={materials.lambert10}
            position={[1.1, -24.21, -74.59]}
          />
          <mesh
            name="pSphere31"
            geometry={nodes.pSphere31.geometry}
            material={materials.lambert19}
            position={[34.92, 0, -54.54]}
          />
        </group>
        <group
          name="pot22"
          position={[3.79, 0.63, 0.07]}
          rotation={[Math.PI / 2, 0.27, 0]}
          scale={0.01}
        >
          <mesh
            name="polySurface249"
            geometry={nodes.polySurface249.geometry}
            material={materials.lambert13}
            position={[111.59, 0, 41.34]}
          />
          <mesh
            name="polySurface263"
            geometry={nodes.polySurface263.geometry}
            material={materials.lambert12}
            position={[111.59, 0, 41.34]}
          />
          <mesh
            name="polySurface264"
            geometry={nodes.polySurface264.geometry}
            material={materials.lambert12}
            position={[90.32, 0, 51.16]}
            scale={[0.9, 1, 0.9]}
          />
          <mesh
            name="polySurface265"
            geometry={nodes.polySurface265.geometry}
            material={materials.lambert12}
            position={[100.42, -8.05, 46.5]}
            scale={[0.95, 1.05, 0.95]}
          />
        </group>
        <group
          name="Plant"
          position={[4.46, 0.98, 0.13]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="polySurface258"
            geometry={nodes.polySurface258.geometry}
            material={materials.brown}
            position={[188.44, -11.19, 60.04]}
            scale={0.82}
          />
          <mesh
            name="polySurface378"
            geometry={nodes.polySurface378.geometry}
            material={materials.darkbrown}
            position={[43.98, 28.65, 63.46]}
            rotation={[0, -0.34, 0]}
          />
          <group
            name="polySurface379"
            position={[43.98, 33.76, 63.46]}
            rotation={[0, -0.34, 0]}
          >
            <mesh
              name="Mesh066"
              geometry={nodes.Mesh066.geometry}
              material={materials.darkbrown}
            />
            <mesh
              name="Mesh066_1"
              geometry={nodes.Mesh066_1.geometry}
              material={materials.lambert22}
            />
            <mesh
              name="Mesh066_2"
              geometry={nodes.Mesh066_2.geometry}
              material={materials.lambert11}
            />
          </group>
        </group>
        <group
          name="polySurface381"
          position={[4.48, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="polySurface480"
            geometry={nodes.polySurface480.geometry}
            material={materials.lambert12}
            position={[0, 23.96, 0]}
          />
          <mesh
            name="polySurface481"
            geometry={nodes.polySurface481.geometry}
            material={materials.lambert12}
            position={[357.22, 604.88, -365.45]}
            rotation={[2.07, 0.59, 1.04]}
            scale={[2.24, 2.07, 2.31]}
          />
        </group>
        <group
          name="polySurface384"
          position={[7.63, 0.12, 0.12]}
          rotation={[1.37, 1.2, 0.39]}
          scale={0.01}
        >
          <mesh
            name="polySurface385"
            geometry={nodes.polySurface385.geometry}
            material={materials.lambert23}
          />
        </group>
        <group
          name="Cupboard"
          position={[4.48, 0, 0.04]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <group
            name="books1_polySurface201"
            position={[145.2, 115.83, -62.27]}
            rotation={[0, 0.57, 0]}
            scale={[0.72, 0.54, 0.72]}
          >
            <mesh
              name="Mesh090"
              geometry={nodes.Mesh090.geometry}
              material={materials.lambert14}
            />
            <mesh
              name="Mesh090_1"
              geometry={nodes.Mesh090_1.geometry}
              material={materials.lambert7}
            />
            <mesh
              name="Mesh090_2"
              geometry={nodes.Mesh090_2.geometry}
              material={materials.brown}
            />
            <mesh
              name="Mesh090_3"
              geometry={nodes.Mesh090_3.geometry}
              material={materials.lambert27}
            />
            <mesh
              name="Mesh090_4"
              geometry={nodes.Mesh090_4.geometry}
              material={materials.lambert22}
            />
          </group>
          <group
            name="books2_polySurface194"
            position={[72.23, 49.15, -72.14]}
            rotation={[0, 0.5, 0]}
            scale={[0.84, 0.65, 0.84]}
          >
            <mesh
              name="Mesh085"
              geometry={nodes.Mesh085.geometry}
              material={materials.lambert16}
            />
            <mesh
              name="Mesh085_1"
              geometry={nodes.Mesh085_1.geometry}
              material={materials.lambert7}
            />
            <mesh
              name="Mesh085_2"
              geometry={nodes.Mesh085_2.geometry}
              material={materials.lambert21}
            />
            <mesh
              name="Mesh085_3"
              geometry={nodes.Mesh085_3.geometry}
              material={materials.lambert14}
            />
            <mesh
              name="Mesh085_4"
              geometry={nodes.Mesh085_4.geometry}
              material={materials.lambert27}
            />
          </group>
          <group
            name="books2_polySurface198"
            position={[-24.54, 30.37, -37.34]}
            rotation={[2.73, 1.26, -2.71]}
            scale={0.81}
          >
            <mesh
              name="Mesh081"
              geometry={nodes.Mesh081.geometry}
              material={materials.lambert14}
            />
            <mesh
              name="Mesh081_1"
              geometry={nodes.Mesh081_1.geometry}
              material={materials.lambert7}
            />
            <mesh
              name="Mesh081_2"
              geometry={nodes.Mesh081_2.geometry}
              material={materials.lambert21}
            />
            <mesh
              name="Mesh081_3"
              geometry={nodes.Mesh081_3.geometry}
              material={materials.lambert23}
            />
          </group>
          <group
            name="polySurface128"
            position={[-217.7, -8, -126.79]}
            rotation={[0, 1.31, 0]}
            scale={[1, 0.98, 1]}
          >
            <mesh
              name="Mesh079"
              geometry={nodes.Mesh079.geometry}
              material={materials.brown}
            />
            <mesh
              name="Mesh079_1"
              geometry={nodes.Mesh079_1.geometry}
              material={materials.darkbrown}
            />
            <mesh
              name="Mesh079_2"
              geometry={nodes.Mesh079_2.geometry}
              material={materials.lambert21}
            />
          </group>
          <group
            name="polySurface228"
            position={[13.38, 64.26, -143.4]}
            rotation={[2.85, 0.74, -2.81]}
            scale={[0.43, 0.82, 0.43]}
          >
            <mesh
              name="Mesh084"
              geometry={nodes.Mesh084.geometry}
              material={materials.lambert12}
            />
            <mesh
              name="Mesh084_1"
              geometry={nodes.Mesh084_1.geometry}
              material={glassMat}
            />
            <mesh
              name="Mesh084_2"
              geometry={nodes.Mesh084_2.geometry}
              material={materials.lambert13}
            />
          </group>
          <mesh
            name="polySurface376"
            geometry={nodes.polySurface376.geometry}
            material={glassMat}
            position={[22.53, 51.88, -136.08]}
            rotation={[2.98, 0.75, -3.06]}
            scale={[0.43, 0.82, 0.43]}
          />
          <mesh
            name="polySurface376001"
            geometry={nodes.polySurface376001.geometry}
            material={materials.darkbrown}
            position={[22.53, 51.88, -136.08]}
            rotation={[2.98, 0.75, -3.06]}
            scale={[0.43, 0.82, 0.43]}
          />
          <group
            name="polySurface377"
            position={[31.15, 51.88, -148.24]}
            rotation={[2.98, 0.75, -3.06]}
            scale={[0.43, 0.82, 0.43]}
          >
            <mesh
              name="Mesh086"
              geometry={nodes.Mesh086.geometry}
              material={materials.lambert12}
            />
            <mesh
              name="Mesh086_1"
              geometry={nodes.Mesh086_1.geometry}
              material={glassMat}
            />
            <mesh
              name="Mesh086_2"
              geometry={nodes.Mesh086_2.geometry}
              material={materials.lambert13}
            />
          </group>
          <group
            name="polySurface396"
            position={[3.65, 8.5, -0.46]}
            scale={[1, 0.93, 1]}
          >
            <mesh
              name="Mesh091"
              geometry={nodes.Mesh091.geometry}
              material={glassMat}
            />
            <mesh
              name="Mesh091_1"
              geometry={nodes.Mesh091_1.geometry}
              material={materials.darkbrown}
            />
            <mesh
              name="Mesh091_2"
              geometry={nodes.Mesh091_2.geometry}
              material={materials.lambert13}
            />
          </group>
          <group
            name="polySurface401"
            position={[34.25, 116.04, -52.34]}
            rotation={[0, 1.25, 0]}
          >
            <mesh
              name="Mesh092"
              geometry={nodes.Mesh092.geometry}
              material={materials.lambert7}
            />
            <mesh
              name="Mesh092_1"
              geometry={nodes.Mesh092_1.geometry}
              material={materials.lambert27}
            />
          </group>
          <group
            name="polySurface403"
            position={[115.79, 116.04, -178.44]}
            rotation={[0, -1.05, 0]}
          >
            <mesh
              name="Mesh093"
              geometry={nodes.Mesh093.geometry}
              material={materials.lambert7}
            />
            <mesh
              name="Mesh093_1"
              geometry={nodes.Mesh093_1.geometry}
              material={materials.lambert27}
            />
          </group>
          <group
            name="polySurface477"
            position={[94.78, 25.1, 118.24]}
            rotation={[1.71, -0.05, 1.75]}
            scale={[1, 1, 0.92]}
          >
            <mesh
              name="Mesh094"
              geometry={nodes.Mesh094.geometry}
              material={materials.lambert7}
            />
            <mesh
              name="Mesh094_1"
              geometry={nodes.Mesh094_1.geometry}
              material={materials.lambert21}
            />
            <mesh
              name="Mesh094_2"
              geometry={nodes.Mesh094_2.geometry}
              material={materials.lambert14}
            />
          </group>
          <mesh
            name="pPlane35"
            geometry={nodes.pPlane35.geometry}
            material={materials.lambert7}
            position={[323.64, 387.03, -59.11]}
            rotation={[2.08, -1.04, 0.52]}
            scale={[1.16, 0.84, 1.16]}
          />
          <mesh
            name="pPlane50"
            geometry={nodes.pPlane50.geometry}
            material={materials.lambert7}
            position={[262.27, -70.19, -102.75]}
            rotation={[-1.61, -0.34, 2.88]}
            scale={[1, 0.73, 1]}
          />
          <mesh
            name="pPlane51"
            geometry={nodes.pPlane51.geometry}
            material={materials.lambert7}
            position={[222.85, -85.97, -52.54]}
            rotation={[-1.72, -0.28, 2.66]}
            scale={[1, 0.83, 1]}
          />
          <mesh
            name="pPlane52"
            geometry={nodes.pPlane52.geometry}
            material={materials.lambert7}
            position={[226.36, -25.82, -103.86]}
            rotation={[-1.61, -0.34, 2.88]}
            scale={[0.77, 0.73, 0.77]}
          />
          <mesh
            name="pPlane53"
            geometry={nodes.pPlane53.geometry}
            material={materials.lambert7}
            position={[-107, 184.99, -172.36]}
            rotation={[1.1, 1.1, 0.58]}
            scale={[0.77, 0.73, 0.77]}
          />
          <mesh
            name="pPlane54"
            geometry={nodes.pPlane54.geometry}
            material={materials.lambert7}
            position={[-179.06, 199.86, -191.39]}
            rotation={[1.1, 1.1, 0.58]}
            scale={[1, 0.73, 1]}
          />
          <mesh
            name="pPlane55"
            geometry={nodes.pPlane55.geometry}
            material={materials.lambert7}
            position={[286.01, 115.1, -152.98]}
            rotation={[-0.29, -1.45, -0.87]}
            scale={[0.68, 0.44, 0.68]}
          />
          <mesh
            name="pPlane56"
            geometry={nodes.pPlane56.geometry}
            material={materials.lambert7}
            position={[258.82, 195.55, -146.82]}
            rotation={[1.5, -1.11, 1.07]}
            scale={[0.68, 0.44, 0.68]}
          />
          <mesh
            name="pPlane57"
            geometry={nodes.pPlane57.geometry}
            material={materials.lambert7}
            position={[223.45, 142.04, -150.09]}
            rotation={[0.86, -1.28, 0.26]}
            scale={[0.52, 0.44, 0.52]}
          />
          <group
            name="pPlane58"
            position={[64.58, 15.96, 42.94]}
            rotation={[0, -1.26, 0]}
          >
            <mesh
              name="Mesh082"
              geometry={nodes.Mesh082.geometry}
              material={materials.Walls}
            />
            <mesh
              name="Mesh082_1"
              geometry={nodes.Mesh082_1.geometry}
              material={materials.lambert7}
            />
            <mesh
              name="Mesh082_2"
              geometry={nodes.Mesh082_2.geometry}
              material={materials.lambert11}
            />
            <mesh
              name="Mesh082_3"
              geometry={nodes.Mesh082_3.geometry}
              material={materials.lambert22}
            />
          </group>
          <group
            name="pPlane59"
            position={[64.58, 29.29, 42.94]}
            rotation={[0, -1.26, 0]}
          >
            <mesh
              name="Mesh080"
              geometry={nodes.Mesh080.geometry}
              material={materials.Walls}
            />
            <mesh
              name="Mesh080_1"
              geometry={nodes.Mesh080_1.geometry}
              material={materials.lambert7}
            />
            <mesh
              name="Mesh080_2"
              geometry={nodes.Mesh080_2.geometry}
              material={materials.lambert11}
            />
          </group>
        </group>
        <pointLight
          name="Point"
          intensity={271.76}
          decay={2}
          color="#ff961a"
          position={[4.17, 1.16, 0.89]}
        />
        <pointLight
          name="Point001"
          intensity={271.76}
          decay={2}
          color="#ff3900"
          position={[4.09, 1.17, 0.83]}
        />
        <pointLight
          name="Point002"
          intensity={86.96}
          decay={2}
          color="#ff3900"
          position={[3.86, 1.4, 1.27]}
        />
        <pointLight
          name="Point003"
          intensity={86.96}
          decay={2}
          color="#ff3900"
          position={[3.79, 1.37, 1.28]}
        />
        <pointLight
          name="Point004"
          intensity={86.96}
          decay={2}
          color="#ff961a"
          position={[3.79, 1.37, 1.28]}
        />
        <pointLight
          name="Point005"
          intensity={86.96}
          decay={2}
          color="#ff3104"
          position={[3.39, 1.33, 0.89]}
        />
        <pointLight
          name="Point006"
          intensity={86.96}
          decay={2}
          color="#ff3900"
          position={[3.49, 1.28, 0.77]}
        />
        <pointLight
          name="Point007"
          intensity={86.96}
          decay={2}
          color="#ff3900"
          position={[3.43, 1.24, 0.84]}
        />
        <pointLight
          name="Point008"
          intensity={86.96}
          decay={2}
          color="#ff3900"
          position={[5.93, -0.2, 1.26]}
        />
        <pointLight
          name="Point009"
          intensity={86.96}
          decay={2}
          color="#ff3900"
          position={[5.94, -0.27, 1.21]}
        />
        <pointLight
          name="Point010"
          intensity={86.96}
          decay={2}
          color="#ff3900"
          position={[5.87, -0.25, 1.26]}
        />
        <pointLight
          name="Point011"
          intensity={100}
          decay={1.2}
          color="#14a125"
          position={[3.85, -1.13, 0.68]}
        />
        <mesh
          name="pCube50"
          geometry={nodes.pCube50.geometry}
          material={materials.brown}
          position={[3.86, 1.41, 1.03]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.004, 0.01, 0.01]}
        />
        <mesh
          name="pCube126"
          geometry={nodes.pCube126.geometry}
          material={materials.brown}
          position={[3.86, 1.39, 1.42]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.004, 0.01, 0.01]}
        />
        <group
          name="pCube128"
          position={[4.38, 1.58, 1.51]}
          rotation={[Math.PI / 2, Math.PI / 2, 0]}
          scale={[0, 0.01, 0.01]}
        >
          <mesh
            name="Mesh007"
            geometry={nodes.Mesh007.geometry}
            material={materials.Walls}
          />
          <mesh
            name="Mesh007_1"
            geometry={nodes.Mesh007_1.geometry}
            material={materials.lambert11}
          />
        </group>
        <group
          name="pTorus7"
          position={[6.28, -3.27, 0.1]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={0.01}
        >
          <mesh
            name="Mesh008"
            geometry={nodes.Mesh008.geometry}
            material={materials.lambert6}
          />
          <mesh
            name="Mesh008_1"
            geometry={nodes.Mesh008_1.geometry}
            material={materials.brown}
          />
        </group>
        <mesh
          ref={broomRef}
          name="broom"
          geometry={nodes.pCylinder32.geometry}
          material={materials.brown}
          position={[3.04, 3.74, 3.24]}
          rotation={[1.77, 0.08, -1.59]}
          scale={0.01}
        />
        <mesh
          name="pPlane15"
          geometry={nodes.pPlane15.geometry}
          material={materials.lambert7}
          position={[4.79, -0.46, 0.04]}
          rotation={[-Math.PI / 2, 0.48, Math.PI]}
          scale={0.01}
        />
        <group
          name="pPlane33"
          position={[4.48, 4.11, 1.04]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Mesh011"
            geometry={nodes.Mesh011.geometry}
            material={materials.lambert22}
          />
          <mesh
            name="Mesh011_1"
            geometry={nodes.Mesh011_1.geometry}
            material={materials.stown}
          />
        </group>
        <group
          name="books1_polySurface200"
          position={[5.52, 0.8, 0.7]}
          rotation={[-Math.PI / 2, 0.12, Math.PI]}
          scale={[0.009, 0.007, 0.009]}
        >
          <mesh
            name="Mesh012"
            geometry={nodes.Mesh012.geometry}
            material={materials.lambert27}
          />
          <mesh
            name="Mesh012_1"
            geometry={nodes.Mesh012_1.geometry}
            material={materials.lambert7}
          />
          <mesh
            name="Mesh012_2"
            geometry={nodes.Mesh012_2.geometry}
            material={materials.lambert21}
          />
        </group>
        <group
          name="polySurface180"
          position={[4.53, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Mesh013"
            geometry={nodes.Mesh013.geometry}
            material={materials.Walls}
          />
          <mesh
            name="Mesh013_1"
            geometry={nodes.Mesh013_1.geometry}
            material={materials.lambert11}
          />
        </group>
        <group
          // * tube 1
          name="polySurface239"
          position={[3.96, 1.51, -0.24]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.0083}
        >
          <mesh
            name="Mesh014"
            geometry={nodes.Mesh014.geometry}
            material={glassMat}
          />
          <mesh
            name="Mesh014_1"
            geometry={nodes.Mesh014_1.geometry}
            material={materials.lambert12}
          />
          <mesh
            name="Mesh014_2"
            geometry={nodes.Mesh014_2.geometry}
            material={materials.lambert29}
          />
        </group>
        <group
          // * jar_3
          name="polySurface235"
          position={[4.05, 1.63, -0.52]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.0083}
        >
          <mesh
            name="Mesh015"
            geometry={nodes.Mesh015.geometry}
            material={glassMat}
          />
          <mesh
            name="Mesh015_1"
            geometry={nodes.Mesh015_1.geometry}
            material={materials.darkbrown}
          />
        </group>
        <group
          name="polySurface267"
          position={[4.45, -1.02, 0.05]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={0.01}
        >
          <mesh
            name="Mesh017"
            geometry={nodes.Mesh017.geometry}
            material={materials.stown}
          />
          <mesh
            name="Mesh017_1"
            geometry={nodes.Mesh017_1.geometry}
            material={materials.brown}
          />
        </group>
        <mesh
          name="polySurface284"
          geometry={nodes.polySurface284.geometry}
          material={materials.lambert12}
          position={[3.5, 2.47, 0.06]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <group
          name="polySurface317"
          position={[4.48, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Mesh019"
            geometry={nodes.Mesh019.geometry}
            material={materials.darkbrown}
          />
          <mesh
            name="Mesh019_1"
            geometry={nodes.Mesh019_1.geometry}
            material={materials.lambert11}
          />
        </group>
        <group
          name="polySurface324"
          position={[4.53, -0.03, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Mesh020"
            geometry={nodes.Mesh020.geometry}
            material={materials.darkbrown}
          />
          <mesh
            name="Mesh020_1"
            geometry={nodes.Mesh020_1.geometry}
            material={materials.lambert11}
          />
        </group>
        <group
          name="polySurface335"
          position={[4.1475, 0.040744, -0.328466]}
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[0.008, 0.009, 0.012]}
        >
          <mesh
            name="Mesh022"
            geometry={nodes.Mesh022.geometry}
            material={materials.stown}
          />
          <mesh
            name="Mesh022_1"
            geometry={nodes.Mesh022_1.geometry}
            material={materials.lambert21}
          />
        </group>
        <mesh
          name="pCylinder82"
          geometry={nodes.pCylinder82.geometry}
          material={materials.lambert19}
          position={[6.82, 1.98, 0.04]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.015}
        />
        <group
          name="polySurface338"
          position={[5.46, -1.77, 0.27]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            // * jar_2
            name="Mesh051"
            geometry={nodes.Mesh051.geometry}
            material={glassMat}
          />
          <mesh
            name="Mesh051_1"
            geometry={nodes.Mesh051_1.geometry}
            material={materials.lambert13}
          />
          <mesh
            name="Mesh051_2"
            geometry={nodes.Mesh051_2.geometry}
            material={materials.lambert12}
          />
        </group>
        <group
          // * jar_1
          name="polySurface341"
          position={[5.56, -1.51, 0.03]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Mesh052"
            geometry={nodes.Mesh052.geometry}
            material={glassMat}
          />
          <mesh
            name="Mesh052_1"
            geometry={nodes.Mesh052_1.geometry}
            material={materials.lambert12}
          />
          <mesh
            name="Mesh052_2"
            geometry={nodes.Mesh052_2.geometry}
            material={materials.lambert4}
          />
        </group>
        <mesh
          name="pPlane43"
          geometry={nodes.pPlane43.geometry}
          material={materials.lambert7}
          position={[5.18, 2.3, 2.1]}
          rotation={[2.21, -0.96, -1.02]}
          scale={0.006}
        />
        <mesh
          name="polySurface345"
          geometry={nodes.polySurface345.geometry}
          material={glassMat}
          position={[5.22, -1.1, -0.75]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.017}
        />
        <Float
          floatIntensity={intensity}
          speed={speed}
          floatingRange={[min, max]}
        >
          <group
            name="polySurface350"
            position={[4.48, 0, 0.1]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={0.01}
          >
            <mesh
              name="Mesh055"
              geometry={nodes.Mesh055.geometry}
              material={materials.lambert7}
            />
            <mesh
              name="Mesh055_1"
              geometry={nodes.Mesh055_1.geometry}
              material={materials.lambert1}
            />
          </group>
        </Float>
        <mesh
          name="pCylinder83"
          geometry={nodes.pCylinder83.geometry}
          material={materials.lambert19}
          position={[7.24, 2.36, 1.03]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.015}
        />
        <mesh
          name="pCylinder84"
          geometry={nodes.pCylinder84.geometry}
          material={materials.lambert19}
          position={[7.65, 2.36, 1]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.015}
        />
        <mesh
          name="polySurface365"
          geometry={nodes.polySurface365.geometry}
          material={materials.lambert1}
          position={[4.53, 2.06, 1.68]}
          rotation={[1.55, 0.51, 1.29]}
          scale={0.01}
        />
        <mesh
          name="polySurface366"
          geometry={nodes.polySurface366.geometry}
          material={materials.lambert1}
          position={[6.8, 1.13, 2.08]}
          rotation={[1.55, -0.84, 1.27]}
          scale={0.007}
        />
        <mesh
          name="polySurface367"
          geometry={nodes.polySurface367.geometry}
          material={materials.lambert1}
          position={[5.02, 1.15, 1.46]}
          rotation={[1.2, 0.49, 1.95]}
          scale={0.007}
        />
        <mesh
          name="polySurface368"
          geometry={nodes.polySurface368.geometry}
          material={materials.lambert1}
          position={[4.68, 1.32, 1.55]}
          rotation={[1.27, 0.74, 2.01]}
          scale={0.007}
        />
        <mesh
          name="polySurface331"
          geometry={nodes.polySurface331.geometry}
          material={materials.darkbrown}
          position={[4.48, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <group
          name="polySurface374"
          position={[3.45, 1.37, 0.03]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Mesh064"
            geometry={nodes.Mesh064.geometry}
            material={materials.darkbrown}
          />
          <mesh
            name="Mesh064_1"
            geometry={nodes.Mesh064_1.geometry}
            material={materials.lambert21}
          />
          <mesh
            //* tube 3
            name="Mesh064_2"
            geometry={nodes.Mesh064_2.geometry}
            material={glassMat}
          />
        </group>
        <group
          name="pPlane49"
          position={[4.48, 0, -0.01]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Mesh065"
            geometry={nodes.Mesh065.geometry}
            material={materials.lambert21}
          />
          <mesh
            name="Mesh065_1"
            geometry={nodes.Mesh065_1.geometry}
            material={materials.Walls}
          />
          <mesh
            name="Mesh065_2"
            geometry={nodes.Mesh065_2.geometry}
            material={materials.lambert7}
          />
          <mesh
            name="Mesh065_3"
            geometry={nodes.Mesh065_3.geometry}
            material={materials.lambert11}
          />
          <mesh
            name="Mesh065_4"
            geometry={nodes.Mesh065_4.geometry}
            material={materials.lambert14}
          />
          <mesh
            name="Mesh065_5"
            geometry={nodes.Mesh065_5.geometry}
            material={materials.lambert9}
          />
          <mesh
            name="Mesh065_6"
            geometry={nodes.Mesh065_6.geometry}
            material={materials.lambert22}
          />
        </group>
        <group
          name="hat2"
          position={[3.53, -0.58, 0.05]}
          rotation={[Math.PI / 2, -0.63, 0]}
          scale={0.01}
        >
          <mesh
            name="Mesh069"
            geometry={nodes.Mesh069.geometry}
            material={materials.lambert27}
          />
          <mesh
            name="Mesh069_1"
            geometry={nodes.Mesh069_1.geometry}
            material={materials.lambert7}
          />
          <mesh
            name="Mesh069_2"
            geometry={nodes.Mesh069_2.geometry}
            material={materials.lambert21}
          />
        </group>
        <group
          name="polySurface383"
          position={[4.48, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Mesh072"
            geometry={nodes.Mesh072.geometry}
            material={materials.lambert23}
          />
          <mesh
            name="Mesh072_1"
            geometry={nodes.Mesh072_1.geometry}
            material={materials.lambert1}
          />
          <mesh
            name="Mesh072_2"
            geometry={nodes.Mesh072_2.geometry}
            material={materials.lambert7}
          />
        </group>
        <group
          name="polySurface394"
          position={[4.59, -0.22, 0.16]}
          rotation={[1.45, 0.01, -0.05]}
          scale={[0.009, 0.01, 0.009]}
        >
          <mesh
            name="Mesh074"
            geometry={nodes.Mesh074.geometry}
            material={materials.lambert1}
          />
          <mesh
            name="Mesh074_1"
            geometry={nodes.Mesh074_1.geometry}
            material={materials.lambert7}
          />
        </group>
        <mesh
          name="polySurface395"
          geometry={nodes.polySurface395.geometry}
          material={materials.lambert23}
          position={[4.45, -0.85, 0.05]}
          rotation={[-Math.PI / 2, -1.46, -3.05]}
          scale={0.01}
        />
        <group
          name="polySurface397"
          position={[4.48, 0, 0.04]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Mesh076"
            geometry={nodes.Mesh076.geometry}
            material={materials.lambert21}
          />
          <mesh
            name="Mesh076_1"
            geometry={nodes.Mesh076_1.geometry}
            material={materials.lambert7}
          />
        </group>
        <group
          name="polySurface399"
          position={[4.48, 0, 0.04]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            name="Mesh077"
            geometry={nodes.Mesh077.geometry}
            material={materials.lambert21}
          />
          <mesh
            name="Mesh077_1"
            geometry={nodes.Mesh077_1.geometry}
            material={materials.lambert7}
          />
        </group>
        <mesh
          name="polySurface474"
          geometry={nodes.polySurface474.geometry}
          material={materials.stown}
          position={[4.48, 0, 0.05]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="polySurface478"
          geometry={nodes.polySurface478.geometry}
          material={materials.lambert23}
          position={[4.48, 0, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        />

        <group
          name="polySurface482"
          position={[2.4, -0.7, -0.45]}
          rotation={[Math.PI / 2, 1.46, 0]}
          scale={0.0083}
        >
          <mesh
            name="Mesh102"
            geometry={nodes.Mesh102.geometry}
            material={materials.lambert12}
          />
          <mesh
            name="Mesh102_1"
            geometry={nodes.Mesh102_1.geometry}
            material={materials.lambert29}
          />
          <mesh
            name="Mesh102_2"
            geometry={nodes.Mesh102_2.geometry}
            //* tube 2
            material={glassMat}
          />
        </group>
        <mesh
          name="pSphere33"
          geometry={nodes.pSphere33.geometry}
          material={materials.Walls}
          position={[6.56, 0.73, 1.01]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.008}
        />
        <group
          name="polySurface484"
          position={[5.26, -2.51, -0.08]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            // * jar_4
            name="Mesh104"
            geometry={nodes.Mesh104.geometry}
            material={glassMat}
          />
          <mesh
            name="Mesh104_1"
            geometry={nodes.Mesh104_1.geometry}
            material={materials.lambert13}
          />
          <mesh
            name="Mesh104_2"
            geometry={nodes.Mesh104_2.geometry}
            material={materials.lambert12}
          />
        </group>
        <group
          name="polySurface490"
          position={[3.35, 0.69, 0.73]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.01}
        >
          <mesh
            //  * jar_5
            name="Mesh105"
            geometry={nodes.Mesh105.geometry}
            material={glassMat}
          />
          <mesh
            name="Mesh105_1"
            geometry={nodes.Mesh105_1.geometry}
            material={materials.lambert12}
          />
          <mesh
            name="Mesh105_2"
            geometry={nodes.Mesh105_2.geometry}
            material={materials.lambert10}
          />
        </group>
        <mesh
          name="polySurface345001"
          geometry={nodes.polySurface345001.geometry}
          material={materials.darkbrown}
          position={[5.22, -1.1, -0.75]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.017}
        />
        <mesh
          name="polySurface482001"
          geometry={nodes.polySurface482001.geometry}
          material={materials.lambert29}
          position={[2.4, -0.7, -0.45]}
          rotation={[Math.PI / 2, 1.46, 0]}
          scale={0.0083}
        />
        <mesh
          name="polySurface345002"
          geometry={nodes.polySurface345002.geometry}
          material={materials.lambert29}
          position={[5.22, -1.1, -0.75]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.02}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/static/wizards_room/final_room.glb");
export default Room;
